import { defineTerm } from './definitions';
import type { Lesson } from './types';

export const coreLessons: Lesson[] = [
  {
    id: 'mathematical-language', title: 'Read the mathematics', tier: 'start',
    intro: 'Translate the question before calculating. The command tells you what to do; the mathematical nouns tell you which objects and relationships matter.',
    goals: ['Distinguish expressions, equations and inequalities.', 'Use command terms and show clear mathematical reasoning.'],
    terms: [
      defineTerm('Fraction'),
      defineTerm('Numerator'),
      defineTerm('Denominator'),
      defineTerm('Term'),
      defineTerm('Factor'),
      defineTerm('Inequality'),
      defineTerm('Expression'),
      defineTerm('Equation'),
      defineTerm('Variable'),
      defineTerm('Coefficient'),
      defineTerm('Constant'),
      defineTerm('Substitute'),
      defineTerm('Equivalent'),
    ],
    sections: [
      { title: 'Write a readable solution', text: 'Define your variable, show one justified transformation per line and finish with a statement answering the question. Keep an exact value such as √13 until the final rounding step. An equals sign joins equal values: do not use it as a replacement for “then”. Include units for lengths and square units for areas.' },
      { title: 'Read the command', text: '“State” normally needs a concise result. “Calculate” needs a numerical result with relevant working. “Solve” asks for every permitted value satisfying the equation or inequality. “Show that” gives the destination: you must provide a valid route to it. “Justify” requires mathematical reasons, not merely a repeated answer. Use the command-term reference for more examples.' },
      { title: 'MYP reasoning habits', text: 'Practise knowledge and understanding (Criterion A), pattern investigation (B), communication (C) and applying mathematics in a context (D). These are useful study lenses, not a claim about this assessment’s format or marks. For a pattern, distinguish finding a possible rule, checking it and proving why it works.' },
      { title: 'Investigating a pattern · Criterion B', text: 'Describe what changes using numbers and words, write a general rule with a defined index, test it with further cases and justify why it works. Distinguish “verify” (check a claim in specified cases) from a general proof. The sequences lesson gives a complete model of this process.' },
      { title: 'Applying mathematics · Criterion D', text: 'Identify the relevant information, define variables with units, choose a suitable model and solve it. Then interpret the answer in the original situation, state the needed accuracy and consider whether it is reasonable. Explain assumptions and limitations: a linear cost model might assume a constant rate and no extra fees. A calculation without this interpretation is an unfinished contextual answer.' },
    ],
    example: { prompt: 'Solve 3x + 5 = 17 and verify your solution.', steps: ['Subtract 5 from both sides: 3x = 12.', 'Divide both sides by 3: x = 4.', 'Verify in the original equation: 3(4) + 5 = 17. Therefore x = 4 is a solution.'] },
    pitfalls: ['Do not turn a chain of different calculations into one false chain of equalities.', 'Use parentheses for negative substitutions: (−3)² = 9, but −3² = −9.'],
    questions: [
      { prompt: 'Identify the coefficient and constant in 7 − 3x.', hint: 'Rewrite it as −3x + 7.', steps: ['The coefficient of x is −3, including its sign.', 'The constant is 7.'] },
      { prompt: 'Bike hire costs AED 8 plus AED 3 per hour. With AED 26 available, model the cost and find the maximum hire time. State an assumption.', hint: 'Define h as hours and express the budget as an inequality.', steps: ['Let h be the hire time in hours, with h ≥ 0. Cost C = 8 + 3h AED.', 'The budget gives 8 + 3h ≤ 26, so h ≤ 6. The maximum is 6 hours.', 'Check: 8 + 3(6) = AED 26. This assumes the rate stays constant and there are no additional fees. If whole hours are charged, 6 hours is still feasible.'] },
    ],
  },
  {
    id: 'proof-and-generalisation', title: 'Proof & generalisation', tier: 'core', drFrost: '454',
    intro: 'A pattern suggests a rule. A proof explains why the rule must hold under stated assumptions. Learn to test a conjecture without confusing evidence with certainty.',
    goals: ['Form a general rule from a pattern.', 'Verify examples and justify a generalisation.', 'Use an algebraic proof or a counterexample.'],
    terms: [
      defineTerm('Generalisation'),
      defineTerm('Conjecture'),
      defineTerm('Proof'),
      defineTerm('Counterexample'),
      defineTerm('Integer'),
      defineTerm('Consecutive'),
    ],
    sections: [
      { title: 'Investigate in a useful order', text: 'Record cases accurately, describe a pattern in words, propose a rule and test it on cases beyond those used to create it. State the domain, such as positive integers n. Then explain the structure that produces the rule. A table alone does not establish that a rule works for every possible input.' },
      { title: 'Represent the whole class', text: 'Use 2n for an even integer and 2n + 1 for an odd integer, with n an integer. Use different letters for independent numbers: two odd integers need not be equal. Rewrite the expression into the form you need to establish.', formula: 'Even: 2n. Odd: 2n + 1. Multiple of k: kn (n an integer).' },
      { title: 'Disprove carefully', text: 'To disprove “all”, one valid counterexample is enough. It must obey the assumptions and fail the conclusion. To prove “all”, many successful examples are not enough. For geometric patterns, a diagram-based explanation can justify why each new term grows in the stated way.' },
    ],
    example: { prompt: 'Prove that the sum of any two odd integers is even.', steps: ['Let the integers be 2m + 1 and 2n + 1, where m and n are integers.', 'Their sum is 2m + 2n + 2 = 2(m + n + 1).', 'm + n + 1 is an integer, so the sum is a multiple of 2 and therefore even.'] },
    pitfalls: ['Two examples do not prove a universal claim.', 'Do not assume the conclusion you are trying to prove.', 'State that parameters are integers when using parity arguments.'],
    questions: [
      { prompt: 'Prove that the sum of three consecutive integers is divisible by 3.', hint: 'Represent them as n, n + 1 and n + 2.', steps: ['The sum is n + (n + 1) + (n + 2) = 3n + 3.', 'This equals 3(n + 1); n + 1 is an integer, so the sum is divisible by 3.'] },
      { prompt: 'Disprove: “For every positive integer n, n² + n + 1 is prime.”', hint: 'Try n = 4.', steps: ['At n = 4 the expression is 16 + 4 + 1 = 21.', '21 = 3 × 7 is not prime. Since 4 is an allowed input, this counterexample disproves the statement.'] },
    ],
  },
  {
    id: 'coordinate-geometry', title: 'Coordinates, distance & gradient', tier: 'core', drFrost: '266 · 289 · 265 · 270', visual: 'coordinate',
    intro: 'Read a point as an ordered pair. Use the horizontal and vertical changes between two points to find a midpoint, a distance and the steepness of a line.',
    goals: ['Calculate a distance, midpoint and gradient.', 'Recognise horizontal and vertical lines.', 'Connect a gradient and intercept to a straight-line equation.'],
    terms: [
      defineTerm('Coordinate'),
      defineTerm('Gradient / slope'),
      defineTerm('Midpoint'),
      defineTerm('Distance formula'),
      defineTerm('Intercept'),
      defineTerm('Undefined gradient'),
    ],
    sections: [
      { title: 'Keep the coordinate order', text: 'For A(x₁, y₁) and B(x₂, y₂), calculate both changes in the same direction. A negative gradient means y decreases as x increases. Horizontal lines have gradient zero. Vertical lines have equation x = constant and cannot be written as y = mx + c with a finite gradient.', formula: 'm = (y₂ − y₁)/(x₂ − x₁), provided x₂ ≠ x₁.' },
      { title: 'Average for midpoint; Pythagoras for distance', text: 'Average the two x-coordinates and the two y-coordinates separately to find the midpoint. Distance is non-negative. Squaring the coordinate differences means reversing both endpoints does not change the distance.', formula: 'M = ((x₁ + x₂)/2, (y₁ + y₂)/2).  d = √((x₂ − x₁)² + (y₂ − y₁)²).' },
      { title: 'Build a line equation', text: 'In y = mx + c, m is gradient and c is the y-coordinate where x = 0. After finding m, substitute one known point to find c. Alternatively use the point–gradient form. Finally substitute the other point to check your equation.', formula: 'y − y₁ = m(x − x₁)' },
    ],
    example: { prompt: 'For A(−2, 1) and B(4, 9), find the gradient, midpoint, distance and line equation.', steps: ['Δx = 4 − (−2) = 6 and Δy = 9 − 1 = 8, so m = 8/6 = 4/3.', 'M = ((−2 + 4)/2, (1 + 9)/2) = (1, 5).', 'd = √(6² + 8²) = √100 = 10 units.', 'Use A: 1 = (4/3)(−2) + c, so c = 11/3. The line is y = (4/3)x + 11/3.', 'Check B: (4/3)(4) + 11/3 = 27/3 = 9.'] },
    pitfalls: ['Do not reverse only one coordinate subtraction in the gradient.', 'A midpoint is a point; a distance is a length.', 'The gradient of a vertical line is undefined, not zero.'],
    questions: [
      { prompt: 'For P(1, −2) and Q(7, 6), find the gradient, midpoint and distance.', hint: 'The horizontal and vertical changes are 6 and 8.', steps: ['m = 8/6 = 4/3.', 'M = ((1 + 7)/2, (−2 + 6)/2) = (4, 2).', 'd = √(6² + 8²) = 10 units.'] },
      { prompt: 'State the equation and gradient of the line through (3, −1) and (3, 8).', hint: 'Both points have the same x-coordinate.', steps: ['The equation is x = 3.', 'The horizontal change is zero, so the gradient is undefined. The line is vertical.'] },
    ],
  },
  {
    id: 'linear-equations', title: 'Solve linear equations', tier: 'core', drFrost: '198 · 199 · 254 · 257 · 258 · 259',
    intro: 'An equation is a balance. Apply the same valid operation to both sides until the variable is isolated, then check the result in the original equation.',
    goals: ['Solve equations with brackets, fractions and variables on both sides.', 'Recognise no solution and infinitely many solutions.'],
    terms: [
      defineTerm('Linear equation'),
      defineTerm('Solution'),
      defineTerm('Inverse operation'),
      defineTerm('Expand'),
      defineTerm('Like terms'),
    ],
    sections: [
      { title: 'A reliable sequence', text: 'Expand brackets, combine like terms, collect variable terms on one side and constants on the other, then divide by the non-zero coefficient. This order is helpful but not compulsory. What matters is preserving equality at each step. Write the operation instead of relying on a vague “move and change sign”.' },
      { title: 'Clear fractions safely', text: 'Multiply every term on both sides by a common denominator. A numerator containing several terms stays in brackets until you expand it. If a denominator contains a variable, first record excluded values; that is a rational equation, covered in the recap.', formula: '(x − 1)/3 + (x + 2)/2 = 4  →  2(x − 1) + 3(x + 2) = 24' },
      { title: 'When x disappears', text: 'If simplification gives a false statement such as 2 = 5, there is no solution. If it gives an identity such as 2 = 2, every value in the permitted domain is a solution. Do not divide by a zero coefficient or invent a single answer.' },
    ],
    example: { prompt: 'Solve (x − 1)/3 + (x + 2)/2 = 4.', steps: ['Multiply every term by 6: 2(x − 1) + 3(x + 2) = 24.', 'Expand: 2x − 2 + 3x + 6 = 24, so 5x + 4 = 24.', 'Subtract 4 and divide by 5: x = 4.', 'Check: (4 − 1)/3 + (4 + 2)/2 = 1 + 3 = 4.'] },
    pitfalls: ['Distribute a negative sign to every term inside brackets.', 'When clearing fractions, multiply every term, including the right-hand side.', 'Check in the original equation, not just your final simplified line.'],
    questions: [
      { prompt: 'Solve 4(2x − 3) = 3x + 8.', hint: 'Expand the left-hand side first.', steps: ['8x − 12 = 3x + 8, so 5x = 20.', 'x = 4. Check: 4(8 − 3) = 20 and 12 + 8 = 20.'] },
      { prompt: 'Compare 2(x + 3) = 2x + 6 with 2(x + 3) = 2x + 7.', hint: 'Subtract 2x after expanding.', steps: ['The first gives 6 = 6, so all real x satisfy it.', 'The second gives 6 = 7, so it has no solution.'] },
    ],
  },
  {
    id: 'simultaneous-equations', title: 'Simultaneous equations', tier: 'core', drFrost: '275 · 276 · 419 · 421',
    intro: 'A simultaneous solution satisfies every equation in a system at the same time. Graphically, it is a point shared by the lines.',
    goals: ['Use elimination and substitution.', 'Interpret one, no or infinitely many common solutions.', 'Check a solution in both equations.'],
    terms: [
      defineTerm('Simultaneous equations'),
      defineTerm('Elimination'),
      defineTerm('Substitution method'),
      defineTerm('Intersection'),
    ],
    sections: [
      { title: 'Choose the method', text: 'Substitution is convenient when one equation already isolates a variable. Elimination is convenient when coefficients match or can be made to match. Multiply the whole equation, including its constant, when preparing to eliminate. Use addition for opposite coefficients and subtraction for equal coefficients.' },
      { title: 'Finish the pair', text: 'Finding x is only half the work. Substitute it into an original equation to calculate y. Write the solution as x = …, y = … or as an ordered pair (x, y). Substitute both values into both original equations to check.' },
      { title: 'Read the geometry', text: 'Two distinct non-parallel lines have one common point. Distinct parallel lines have no common solution. Two equations representing the same line have infinitely many solutions. Algebraically these last two cases produce a contradiction or an identity after elimination.' },
    ],
    example: { prompt: 'Solve 2x + 3y = 17 and 3x − 2y = 6.', steps: ['Multiply the first equation by 2: 4x + 6y = 34.', 'Multiply the second by 3: 9x − 6y = 18.', 'Add: 13x = 52, so x = 4.', 'Substitute: 8 + 3y = 17, so y = 3.', 'Check both: 2(4) + 3(3) = 17 and 3(4) − 2(3) = 6.'] },
    pitfalls: ['Multiplying just the variable terms changes the equation.', 'The pair must satisfy both equations, not just one.', 'Subtract brackets carefully when eliminating.'],
    questions: [
      { prompt: 'Solve y = 2x + 1 and x + y = 10.', hint: 'Substitute 2x + 1 for y in the second equation.', steps: ['x + 2x + 1 = 10 gives 3x = 9, so x = 3.', 'y = 2(3) + 1 = 7. Check: 3 + 7 = 10.'] },
      { prompt: 'How many solutions do 2x + y = 5 and 4x + 2y = 12 have?', hint: 'Double the first equation and compare.', steps: ['Doubling gives 4x + 2y = 10, contradicting 4x + 2y = 12.', 'There is no solution. The graphs are distinct parallel lines.'] },
    ],
  },
  {
    id: 'linear-inequalities', title: 'Inequalities & number lines', tier: 'core', drFrost: '309 · 339 · 340 · 341 · 342', visual: 'inequality',
    intro: 'An inequality often describes a range of solutions. Solve it with balanced operations and show precisely which boundary values are included.',
    goals: ['Solve single and compound linear inequalities.', 'Reverse the sign when multiplying or dividing by a negative.', 'Represent a solution on a number line.'],
    terms: [
      defineTerm('Linear inequality'),
      defineTerm('Strict inequality'),
      defineTerm('Inclusive inequality'),
      defineTerm('Solution set'),
      defineTerm('Compound inequality'),
    ],
    sections: [
      { title: 'The sign-reversal rule', text: 'Adding or subtracting the same number preserves the inequality direction. Multiplying or dividing both sides by a positive number also preserves it. Multiplying or dividing by a negative reverses it, because the number-line order reverses.', formula: '2 < 5, but −2 > −5.  Thus −3x ≥ 9 becomes x ≤ −3.' },
      { title: 'Draw the solution', text: 'Use an open circle for < or > and a filled circle for ≤ or ≥. Shade toward smaller values for “less than” and larger values for “greater than”. For a bounded interval, shade between the endpoints. If integer solutions are requested, list or mark only the integers in the range.' },
      { title: 'Compound conditions', text: 'For a double inequality, apply the same operation to all three parts. “And” means the overlap of the conditions; “or” means their union. Verify a boundary and a sample value inside the region after solving.' },
    ],
    example: { prompt: 'Solve 5 − 2x < 11 and represent the answer.', steps: ['Subtract 5: −2x < 6.', 'Divide by −2 and reverse the sign: x > −3.', 'Draw an open circle at −3 and shade to the right.', 'Check x = 0: 5 < 11 is true. At x = −3, 11 < 11 is false, so the boundary is excluded.'] },
    pitfalls: ['Reverse the sign for negative multiplication or division, not for ordinary subtraction.', 'An open circle excludes the endpoint.', 'Keep the domain: integer answers may be different from a real interval.'],
    questions: [
      { prompt: 'Solve 7 − 3x ≥ 16.', hint: 'After subtracting 7, divide by a negative number.', steps: ['−3x ≥ 9, so x ≤ −3.', 'Use a filled circle at −3 and shade left. At −3, equality holds.'] },
      { prompt: 'Solve −2 < 3x + 1 ≤ 10 and list its integer solutions.', hint: 'Subtract 1 from all three parts, then divide by 3.', steps: ['−3 < 3x ≤ 9 gives −1 < x ≤ 3.', 'The integer solutions are 0, 1, 2 and 3. −1 is excluded.'] },
    ],
  },
  {
    id: 'sets-and-venn', title: 'Sets & Venn diagrams', tier: 'core', drFrost: '243 · 242', visual: 'venn',
    intro: 'A set is a collection of distinct elements. Use notation to describe membership, overlap and complement, then translate it into regions on a Venn diagram.',
    goals: ['Read set notation and list elements.', 'Identify and shade unions, intersections and complements.', 'Use Venn diagrams without double-counting.'],
    terms: [
      defineTerm('Set'),
      defineTerm('Element / member'),
      defineTerm('Universal set'),
      defineTerm('Union'),
      defineTerm('Intersection'),
      defineTerm('Complement'),
      defineTerm('Subset'),
      defineTerm('Empty set'),
      defineTerm('Cardinality'),
      defineTerm('Disjoint sets'),
    ],
    sections: [
      { title: 'Translate the symbols', text: 'The rectangle is the universal set. Circles show membership in A and B. Their overlap belongs to both. A ∩ B′ means inside A but outside B. (A ∪ B)′ means outside both circles, still inside the rectangle. Work from brackets outward when the notation is nested.' },
      { title: 'Shade by membership', text: 'For each region ask two yes/no questions: is it in A, and is it in B? This creates four regions: A only, both, B only and neither. To shade a complement, include every region of U not in the original set. Do not shade beyond the universal rectangle.' },
      { title: 'Count the overlap once', text: 'Adding n(A) and n(B) counts the intersection twice, so subtract it once when finding the union. For “neither”, subtract the union from the universal total. These counting identities apply to finite sets.', formula: 'n(A ∪ B) = n(A) + n(B) − n(A ∩ B)' },
    ],
    example: { prompt: 'Let U = {1, 2, 3, 4, 5, 6}, A = {1, 2, 3}, B = {3, 4}. Find A ∩ B, A ∪ B, A′ and A ∩ B′.', steps: ['Common elements: A ∩ B = {3}.', 'All elements in either set: A ∪ B = {1, 2, 3, 4}.', 'Elements of U outside A: A′ = {4, 5, 6}.', 'Inside A but outside B: A ∩ B′ = {1, 2}.'] },
    pitfalls: ['Union includes the overlap; it is not “one or the other but not both”.', 'A complement depends on the universal set.', '∅ is not the same set as {0}.'],
    questions: [
      { prompt: 'In a group of 30, 18 study French, 15 study Spanish and 7 study both. How many study neither?', hint: 'Find the union before subtracting from 30.', steps: ['At least one language: 18 + 15 − 7 = 26.', 'Neither: 30 − 26 = 4. French only = 11 and Spanish only = 8, which checks: 11 + 7 + 8 + 4 = 30.'] },
      { prompt: 'Describe the region (A ∪ B)′ and rewrite it using an intersection.', hint: 'Outside the union means not in A and not in B.', steps: ['Shade the part of U outside both circles.', '(A ∪ B)′ = A′ ∩ B′. This is one of De Morgan’s laws.'] },
    ],
  },
];
