import type { Term } from './types';
import { definitionSources } from './sources';

// Original bilingual teaching text. Sources verify mathematical content, not quotations.
type Row = [string, string, string, string, string, string, string, string, string?];
// Only these concepts had their Russian terminology independently checked in the
// listed Russian section. Every explanation/example is still authored, not quoted.
const russianSourceCoverage: Record<string, string[]> = {
  ruFractions: ['Fraction', 'Numerator', 'Denominator'],
  ruExpressions: ['Expression', 'Variable', 'Substitute'],
  ruEquation: ['Equation', 'Solution'],
  ruSystems: ['Simultaneous equations'],
  ruSets: ['Intersection', 'Union'],
  ruDomain: ['Excluded value'],
  ruSigns: ['Sign chart', 'Boundary inclusion'],
  ruInequality: ['Inequality', 'Strict inequality'],
};
export const reviewedTerms: Record<string, Term> = {};
const preciseSourceKeys: Record<string, string[]> = {
  Factor: ['quadraticEquations', 'rationalExpressions'],
  Expand: ['distributive'],
  'Universal set': ['setOperations'],
  'Rational equation': ['rationalEquations'],
  Convergence: ['series', 'seriesConvergence'],
};
function group(sourceKeys: string[], rows: Row[]) {
  for (const [term, russianTerm, meaning, meaningRu, example, exampleRu, contrastEn, contrastRu, diagram] of rows) {
    const sources = (preciseSourceKeys[term] ?? sourceKeys).filter(key => definitionSources[key].language !== 'ru' || russianSourceCoverage[key]?.includes(term)).map(key => definitionSources[key]);
    reviewedTerms[term] = { term, meaning, example, ru: { term: russianTerm, meaning: meaningRu, example: exampleRu }, diagram,
      review: { englishTerm: term, russianTerm, contrast: { en: contrastEn, ru: contrastRu }, sources },
      russianEvidence: sources.some(source => source.language === 'ru') ? 'independently-checked' : 'authored-adaptation',
    };
  }
}

group(['fractions', 'ruFractions'], [
  ['Fraction', 'Дробь', 'A quotient written a/b: the numerator a is divided by the non-zero denominator b. For whole-number parts, b specifies equal parts per whole.', 'Запись частного a/b: числитель a делят на ненулевой знаменатель b. В модели долей знаменатель задаёт число равных частей одного целого.', 'Cut one strip into 5 equal parts and shade 3: 3/5 = 3 ÷ 5 = 0.6 of the strip.', 'Полоску делим на 5 равных частей и закрашиваем 3: 3/5 = 3 ÷ 5 = 0,6 полоски.', 'Equal parts are essential. Fractions can exceed 1 or be negative; a single shaded whole illustrates only some fractions.', 'Части должны быть равными. Дробь может быть больше 1 или отрицательной; рисунок одного целого показывает лишь часть случаев.', 'fraction'],
  ['Numerator', 'Числитель', 'The quantity above the fraction bar: the dividend in the division represented by the fraction.', 'Число или выражение над чертой дроби: делимое в действии деления, записанном этой дробью.', 'In 3/5 the numerator is 3; in (x + 2)/7 the entire expression x + 2 is the numerator.', 'В 3/5 числитель — 3; в (x + 2)/7 числитель — всё выражение x + 2.', 'In a positive parts-of-a-whole picture it counts selected parts; it does not tell you how many equal parts form one whole.', 'В модели положительных долей он показывает число взятых частей, а не число частей в одном целом.', 'fraction'],
  ['Denominator', 'Знаменатель', 'The non-zero quantity below the fraction bar: the divisor. For positive integer denominators it names the size of each equal part.', 'Ненулевое число или выражение под чертой дроби: делитель. Положительный целый знаменатель задаёт размер каждой равной доли.', 'In 3/5 the denominator is 5: each part is one fifth. In 2/(x − 4), require x ≠ 4.', 'В 3/5 знаменатель — 5: каждая доля равна одной пятой. Для 2/(x − 4) требуется x ≠ 4.', 'A larger denominator means smaller equal parts of the same whole. Division by zero is undefined.', 'Больший знаменатель означает меньшие доли одного и того же целого. Деление на ноль не определено.', 'fraction'],
]);
group(['language', 'ruExpressions'], [
  ['Expression', 'Выражение', 'A mathematical phrase representing a value: a number, a variable, or quantities joined by operations. An expression alone does not assert equality.', 'Математическая запись значения: число, переменная или сочетание величин и действий. Само выражение не утверждает равенство двух частей.', 'At x = 2, the expression 4x − 3 has value 4 × 2 − 3 = 5.', 'При x = 2 выражение 4x − 3 имеет значение 4 × 2 − 3 = 5.', '4x − 3 is an expression; 4x − 3 = 5 is an equation. Evaluate or simplify an expression; solve an equation.', '4x − 3 — выражение; 4x − 3 = 5 — уравнение. Выражение вычисляют или упрощают, уравнение решают.', 'algebra'],
  ['Term', 'Слагаемое выражения', 'An additive part of an expression, including its sign, at the level where the expression is being split into a sum.', 'Часть выражения, рассматриваемого как сумма, вместе со знаком. Слагаемые выделяют на выбранном уровне скобок.', 'Write 5x − 2y + 8 as 5x + (−2y) + 8: its terms are 5x, −2y and 8.', 'Запишем 5x − 2y + 8 как 5x + (−2y) + 8: слагаемые — 5x, −2y и 8.', 'In 3(x + 2), 3 and x + 2 are factors. In a sequence, “term” instead means an entry.', 'В 3(x + 2) числа 3 и выражение x + 2 — множители. Для последовательности term означает её член.', 'algebra'],
  ['Factor', 'Множитель', 'One of the quantities multiplied together to form a product. Factoring rewrites a sum or another expression as a product.', 'Одна из величин, произведение которых образует данное выражение. Разложить на множители — представить выражение произведением.', '6x + 12 = 6(x + 2): the factored expression has factors 6 and x + 2.', '6x + 12 = 6(x + 2): множители полученного произведения — 6 и x + 2.', 'Factors are multiplied; terms are added. Cancelling across a fraction requires a common non-zero factor of the whole numerator and denominator.', 'Множители перемножают, слагаемые складывают. Сокращать можно общий ненулевой множитель всего числителя и знаменателя.', 'algebra'],
  ['Variable', 'Переменная', 'A symbol whose value can range over a stated set. In an equation it may represent an unknown value to be found.', 'Символ, которому могут соответствовать разные значения из заданного множества. В уравнении он может обозначать неизвестное.', 'In P = 4s, changing side length s from 2 to 3 changes perimeter P from 8 to 12.', 'В P = 4s изменение стороны s от 2 до 3 изменяет периметр P от 8 до 12.', 'A variable need not change during one calculation. State allowed values: for a square side, s > 0.', 'В отдельном вычислении значение переменной может быть фиксировано. Указывайте допустимые значения: для стороны квадрата s > 0.', 'algebra'],
  ['Coefficient', 'Коэффициент', 'The factor multiplying the specified variable part of a term. In these polynomial examples, coefficients are numbers and include their signs.', 'Множитель при указанной буквенной части слагаемого. В этих примерах с многочленами коэффициенты — числа с их знаками.', 'In −6x² + x − 9, the coefficient of x² is −6 and the coefficient of x is 1.', 'В −6x² + x − 9 коэффициент при x² равен −6, а при x равен 1.', '−6 is a coefficient; −6x² is the whole term. A missing written coefficient can mean 1 or −1.', '−6 — коэффициент; −6x² — всё слагаемое. Ненаписанный коэффициент может быть 1 или −1.', 'algebra'],
  ['Constant', 'Постоянная величина; константа', 'A quantity fixed for the situation or relative to the variables under discussion. A constant term contains none of those variables.', 'Величина, фиксированная в данной задаче относительно рассматриваемых переменных. Свободное слагаемое не содержит этих переменных.', 'In 4x − 7, −7 is the constant term and 4 is a constant coefficient.', 'В 4x − 7 число −7 — свободное слагаемое, а 4 — постоянный коэффициент.', 'A constant can be written with a letter: in y = kx, k may be fixed while x and y vary.', 'Константу можно обозначить буквой: в y = kx число k может быть фиксировано, хотя x и y меняются.', 'algebra'],
  ['Substitute', 'Подставить', 'Replace every occurrence of a specified variable with its given value or an equal expression, preserving the operations.', 'Заменить каждое вхождение указанной переменной её значением или равным выражением, сохранив действия.', 'For x = −3, 2x² − 1 = 2(−3)² − 1 = 17.', 'При x = −3 получаем 2x² − 1 = 2(−3)² − 1 = 17.', 'Use brackets around negative replacements. (−3)² is 9, whereas −3² means −(3²) = −9.', 'Отрицательное число подставляйте в скобках. (−3)² равно 9, а −3² означает −(3²) = −9.'],
  ['Expand', 'Раскрыть скобки', 'Use the distributive law to rewrite a product involving a sum as a sum of products.', 'С помощью распределительного закона представить произведение с суммой как сумму произведений.', '−3(2x − 5) = (−3)(2x) + (−3)(−5) = −6x + 15.', '−3(2x − 5) = (−3)(2x) + (−3)(−5) = −6x + 15.', 'Multiply every term inside the bracket. Expanding changes the form, not the value.', 'Умножайте каждое слагаемое в скобках. Раскрытие скобок меняет запись, но не значение.'],
  ['Like terms', 'Подобные слагаемые', 'Terms with identical variable factors raised to identical powers; only their coefficients may differ.', 'Слагаемые с одинаковой буквенной частью, включая степени переменных; различаться могут их коэффициенты.', '7ab − 2ab = 5ab, but 7a + 2a² cannot be combined into one like term.', '7ab − 2ab = 5ab, но 7a + 2a² нельзя привести к одному подобному слагаемому.', 'Constants are like terms with each other. The variable order does not matter: xy and yx have the same variable part.', 'Числовые слагаемые подобны друг другу. Порядок букв не важен: xy и yx имеют одинаковую буквенную часть.'],
]);
group(['equations', 'ruEquation'], [
  ['Equation', 'Уравнение; равенство', 'A statement that two expressions have equal values. Solving an equation with unknowns means finding all permitted values making that statement true.', 'Утверждение о равенстве значений двух выражений. В школьной русской терминологии уравнение содержит неизвестное; решить его — найти все допустимые значения, делающие равенство верным.', '4x − 3 = 9: add 3 to get 4x = 12, then divide by 4 to get x = 3.', '4x − 3 = 9: прибавляем 3, получаем 4x = 12; делим на 4, получаем x = 3.', 'English “equation” can also describe 2 + 3 = 5; Russian school texts usually call this a numerical equality (числовое равенство).', 'Английское equation может относиться и к 2 + 3 = 5; по-русски такую запись обычно называют числовым равенством.', 'algebra'],
  ['Equivalent', 'Равносильный; тождественно равный', 'Equivalent equations have the same solution set on the stated domain. Equivalent expressions have the same value at every permitted input.', 'Равносильные уравнения имеют одинаковое множество решений на заданной области. Тождественно равные выражения совпадают при всех допустимых значениях.', '2x + 6 = 10 and x = 2 are equivalent over ℝ. Also 2(x + 3) and 2x + 6 are equivalent expressions.', '2x + 6 = 10 и x = 2 равносильны на ℝ. Выражения 2(x + 3) и 2x + 6 тождественно равны.', 'Restrictions matter: x/x = 1 only for x ≠ 0. Squaring an equation can add solutions.', 'Ограничения важны: x/x = 1 лишь при x ≠ 0. Возведение уравнения в квадрат может добавить корни.'],
  ['Linear equation', 'Линейное уравнение', 'An equation reducible to a sum of constant multiples of variables equal to a constant, with no variable products or higher powers.', 'Уравнение, приводимое к равенству суммы постоянных кратных переменных и числа, без произведений переменных и степеней выше первой.', '3(x − 2) = 9 becomes 3x − 6 = 9, so x = 5. In two variables, 2x + y = 4 is linear.', '3(x − 2) = 9 приводится к 3x − 6 = 9, откуда x = 5. Уравнение 2x + y = 4 линейно по двум переменным.', 'x² = 4 and xy = 4 are not linear. State the original domain before transformations involving denominators. In ax + b = 0, a ≠ 0 gives one root.', 'x² = 4 и xy = 4 не линейны. До преобразований дробей укажите исходную ОДЗ. В ax + b = 0 при a ≠ 0 корень единственный.'],
  ['Solution', 'Решение; корень уравнения', 'A permitted value, or tuple of values, that makes every required equation or inequality true when substituted.', 'Допустимое значение или набор значений, при подстановке которого все требуемые равенства или неравенства верны.', 'x = 4 solves 2x + 1 = 9 because 2 × 4 + 1 = 9. It also satisfies x > 3.', 'x = 4 — корень 2x + 1 = 9, поскольку 2 × 4 + 1 = 9. Это число также удовлетворяет x > 3.', 'One solution is not necessarily the entire solution set: x² = 4 has both 2 and −2.', 'Одно решение не всегда составляет всё множество решений: у x² = 4 есть корни 2 и −2.'],
  ['Inverse operation', 'Обратное действие', 'An operation that reverses a specified operation on values for which the reversal is valid.', 'Действие, отменяющее указанное действие на значениях, для которых такое обращение допустимо.', 'To undo multiplying x by 5, divide by 5: 5x = 20 gives x = 4.', 'Чтобы отменить умножение x на 5, делим на 5: из 5x = 20 получаем x = 4.', 'Division by zero is unavailable. Squaring is not one-to-one on ℝ, so recovering x from x² requires both possible signs.', 'На ноль делить нельзя. Возведение в квадрат на ℝ не взаимно однозначно: при восстановлении x по x² учитывайте оба знака.'],
  ['Subject of a formula', 'Выражаемая переменная формулы', 'The variable written alone on one side of a formula, with an expression not containing it on the other side.', 'Переменная, стоящая отдельно в одной части формулы; другая часть выражает её через остальные величины.', 'In A = bh/2, h is made the subject by multiplying by 2 and dividing by b: h = 2A/b, b ≠ 0.', 'Из A = bh/2 выражаем h: умножаем на 2 и делим на b, получаем h = 2A/b, b ≠ 0.', 'Rearranging a formula gives a rule in other variables; evaluating it also needs numerical inputs.', 'Выражение переменной даёт правило через другие величины; для численного вычисления нужны их значения.'],
]);
group(['inequalities', 'ruInequality'], [
  ['Inequality', 'Неравенство', 'A comparison of two expressions using <, >, ≤ or ≥. Its solutions make the stated ordering true.', 'Сравнение двух выражений с помощью <, >, ≤ или ≥. Решения превращают это сравнение в верное неравенство.', '2x + 1 < 7 gives 2x < 6 and x < 3. For example, x = 2 works but x = 3 does not.', 'Из 2x + 1 < 7 получаем 2x < 6 и x < 3. Например, x = 2 подходит, а x = 3 — нет.', 'An equation requires equality. An inequality describes ordering; ≤ and ≥ also allow equality.', 'Уравнение требует равенства. Неравенство задаёт порядок; знаки ≤ и ≥ допускают также равенство.', 'inequality'],
  ['Linear inequality', 'Линейное неравенство', 'An inequality whose variable part can be written as a linear expression, such as ax + b < 0 in one variable.', 'Неравенство, в котором зависимость от переменных линейна, например ax + b < 0 для одной переменной.', '5 − 2x < 11 gives −2x < 6, hence x > −3 after dividing by −2.', 'Из 5 − 2x < 11 получаем −2x < 6; деление на −2 даёт x > −3.', 'Multiplying or dividing both sides by a negative number reverses the inequality sign.', 'При умножении или делении обеих частей на отрицательное число знак неравенства меняют на противоположный.', 'inequality'],
  ['Strict inequality', 'Строгое неравенство', 'A comparison using < or >, so equality does not satisfy it.', 'Неравенство со знаком < или >; равенство его не удовлетворяет.', 'x > −3 allows −2.9 and 0, but excludes −3 itself.', 'x > −3 допускает −2,9 и 0, но исключает само число −3.', 'Use an open endpoint on a number line for a finite excluded boundary.', 'На числовой прямой исключённую конечную границу отмечают выколотой точкой.', 'inequality'],
  ['Inclusive inequality', 'Нестрогое неравенство', 'A comparison using ≤ or ≥, allowing equality as well as the indicated strict ordering.', 'Неравенство со знаком ≤ или ≥, допускающее и равенство, и указанное строгое сравнение.', 'x ≤ 4 includes x = 4 because 4 ≤ 4 is true.', 'x ≤ 4 включает x = 4, поскольку 4 ≤ 4 верно.', 'An equality boundary is included only if the original expression is defined there.', 'Граница равенства включается, только если исходное выражение в ней определено.', 'inequality'],
  ['Solution set', 'Множество решений', 'The collection of all permitted inputs satisfying the complete stated condition.', 'Совокупность всех допустимых значений, удовлетворяющих всему заданному условию.', 'Over real numbers, 3x ≤ 6 has solution set (−∞, 2]; over integers, only integers at most 2 belong.', 'На ℝ неравенство 3x ≤ 6 имеет множество решений (−∞, 2]; на ℤ подходят только целые числа, не превосходящие 2.', 'A domain tells which values may be tested; the solution set tells which of them pass the condition.', 'Область допустимых значений задаёт, что можно проверять; множество решений — какие из этих значений удовлетворяют условию.'],
  ['Compound inequality', 'Составное неравенство', 'Two or more inequalities joined by a logical condition such as “and” or “or”. A double inequality usually means both conditions hold.', 'Несколько неравенств, соединённых условием «и» или «или». Двойное неравенство обычно требует одновременного выполнения двух условий.', '−1 < x ≤ 4 means x > −1 AND x ≤ 4, giving the interval (−1, 4].', '−1 < x ≤ 4 означает x > −1 И x ≤ 4; получаем промежуток (−1, 4].', '“And” takes an intersection; “or” takes a union. x < 0 or x > 2 consists of two separate intervals.', '«И» соответствует пересечению, «или» — объединению. x < 0 или x > 2 задаёт два отдельных промежутка.'],
]);

group(['statements', 'proof'], [
  ['Generalisation', 'Обобщение', 'A statement extending a property to an entire specified class of cases, rather than only the examples observed.', 'Утверждение, распространяющее свойство на весь указанный класс случаев, а не только на проверенные примеры.', 'From several examples, propose: n + (n + 1) + (n + 2) is divisible by 3 for every integer n.', 'По примерам предполагаем: n + (n + 1) + (n + 2) делится на 3 при любом целом n.', 'A pattern suggests a generalisation; a proof must justify every case in its stated scope.', 'Закономерность подсказывает обобщение; доказательство должно обосновать все случаи в указанной области.'],
  ['Conjecture', 'Гипотеза', 'A mathematical claim proposed as true but not yet established by a proof in the discussion.', 'Математическое утверждение, предполагаемое верным, но ещё не обоснованное доказательством в данном рассуждении.', 'Seeing 1 + 3 = 4 and 1 + 3 + 5 = 9 suggests that the first n positive odd integers sum to n².', 'Равенства 1 + 3 = 4 и 1 + 3 + 5 = 9 подсказывают: сумма первых n положительных нечётных чисел равна n².', 'Many successful tests do not prove a universal conjecture. One valid counterexample disproves it.', 'Множество удачных проверок не доказывает всеобщую гипотезу. Один допустимый контрпример её опровергает.'],
  ['Proof', 'Доказательство', 'A chain of valid logical deductions from definitions, accepted results and stated assumptions that establishes the claim.', 'Цепочка правильных логических выводов из определений, известных результатов и заданных предпосылок, обосновывающая утверждение.', 'If m and n are integers, (2m + 1) + (2n + 1) = 2(m + n + 1), so the sum of two odd integers is even.', 'Если m и n целые, то (2m + 1) + (2n + 1) = 2(m + n + 1); значит, сумма двух нечётных целых чисел чётна.', 'Checking a few numbers is evidence, not a proof for infinitely many integers. Explain why the general form covers all cases.', 'Проверка нескольких чисел — свидетельство, но не доказательство для бесконечного множества целых. Объясняйте, почему общий вид охватывает все случаи.'],
  ['Counterexample', 'Контрпример', 'A case within the stated assumptions for which a universal claim is false.', 'Случай, удовлетворяющий предпосылкам, но опровергающий утверждение, заявленное для всех таких случаев.', 'The prime number 2 is even, so it refutes “every prime number is odd”.', 'Простое число 2 чётно; поэтому оно опровергает утверждение «каждое простое число нечётно».', 'An example outside the assumptions proves nothing about the claim; one counterexample refutes “all”, not necessarily “some”.', 'Пример вне условий ничего не говорит об утверждении; один контрпример опровергает «все», но не обязательно «некоторые».'],
]);
group(['integers', 'sequences'], [
  ['Integer', 'Целое число', 'A number in ℤ = {…, −2, −1, 0, 1, 2, …}: zero or a positive or negative whole-number value.', 'Число из ℤ = {…, −2, −1, 0, 1, 2, …}: ноль, положительное или отрицательное целое число.', '−8, 0 and 12 are integers; 1/2 is not. The expression 6/3 represents the integer 2.', '−8, 0 и 12 — целые; 1/2 не целое. Дробь 6/3 представляет целое число 2.', 'Classify the value, not the notation: a fraction can represent an integer. “Natural number” conventions differ about including zero.', 'Классифицируйте значение, а не запись: дробь может представлять целое. Включение нуля в натуральные числа зависит от соглашения.'],
  ['Consecutive', 'Последовательные; соседние', 'Immediately following one another in the specified ordered sequence, with no sequence entry skipped.', 'Идущие непосредственно друг за другом в указанной последовательности, без пропуска её членов.', 'Consecutive integers can be written n, n + 1, n + 2; consecutive even integers as 2n, 2n + 2.', 'Соседние целые записывают n, n + 1, n + 2; соседние чётные — 2n, 2n + 2.', 'Consecutive does not always mean a difference of 1: name the sequence being considered.', 'Слово «соседние» не всегда означает разность 1: указывайте, о какой последовательности идёт речь.'],
]);
group(['coordinates'], [
  ['Coordinate', 'Координата', 'One number in an ordered list locating a point relative to a chosen coordinate system; in the plane the order is (x, y).', 'Одно число в упорядоченном наборе, задающем положение точки в выбранной системе; на плоскости порядок записи — (x, y).', 'A(−2, 5) lies 2 units left and 5 units up from the origin.', 'Точка A(−2, 5) расположена на 2 единицы левее и на 5 единиц выше начала координат.', 'The point is an ordered pair; each coordinate is one number. (−2, 5) and (5, −2) are different points.', 'Точку задаёт упорядоченная пара, а каждая координата — одно число. (−2, 5) и (5, −2) — разные точки.', 'coordinate'],
  ['Midpoint', 'Середина отрезка', 'The point on a segment at equal distances from its two endpoints. Its coordinates are the averages of the endpoint coordinates.', 'Точка отрезка, равноудалённая от его концов. Её координаты — средние арифметические соответствующих координат концов.', 'For A(−2, 1), B(4, 9), M = ((−2 + 4)/2, (1 + 9)/2) = (1, 5).', 'Для A(−2, 1), B(4, 9) получаем M = ((−2 + 4)/2, (1 + 9)/2) = (1, 5).', 'Average x with x and y with y. Averaging all four coordinates gives neither a point nor a midpoint.', 'Усредняйте x с x и y с y. Среднее всех четырёх чисел не задаёт середину отрезка.', 'coordinate'],
  ['Distance formula', 'Формула расстояния', 'In perpendicular Cartesian axes with the same length unit, the distance between two points is √((Δx)² + (Δy)²).', 'В прямоугольной системе с одинаковой единицей длины по осям расстояние между точками равно √((Δx)² + (Δy)²).', 'From A(−2, 1) to B(4, 9): Δx = 6, Δy = 8, so d = √(36 + 64) = 10.', 'Для A(−2, 1) и B(4, 9): Δx = 6, Δy = 8, поэтому d = √(36 + 64) = 10.', 'Distance is non-negative and symmetric. Adding coordinate differences instead calculates a different route, not straight-line distance.', 'Расстояние неотрицательно и одинаково в обоих направлениях. Сумма модулей приращений задаёт другой путь, а не прямое расстояние.', 'coordinate'],
  ['Intercept', 'Пересечение с осью', 'A point where a graph meets a coordinate axis. At an x-intercept y = 0; at a y-intercept x = 0.', 'Точка, в которой график встречается с координатной осью. На оси x имеем y = 0, на оси y — x = 0.', 'For y = 2x − 6: setting x = 0 gives (0, −6); setting y = 0 gives (3, 0).', 'Для y = 2x − 6: при x = 0 получаем (0, −6); при y = 0 — (3, 0).', 'A graph may touch an axis without crossing it: y = x² has an x-intercept at (0, 0). State whether giving a point or its coordinate.', 'График может касаться оси, не переходя через неё: у y = x² есть пересечение (0, 0). Различайте точку и её координату.'],
]);
group(['lines'], [
  ['Gradient / slope', 'Угловой коэффициент; наклон', 'For a non-vertical straight line, the constant ratio m = Δy/Δx between changes in its coordinates.', 'Для невертикальной прямой постоянное отношение m = Δy/Δx приращения y к соответствующему приращению x.', 'From A(−2, 1) to B(4, 9), m = (9 − 1)/(4 − (−2)) = 8/6 = 4/3.', 'Для A(−2, 1) и B(4, 9): m = (9 − 1)/(4 − (−2)) = 8/6 = 4/3.', 'Slope is a ratio, not an angle or distance. Use the same endpoint order in both differences.', 'Угловой коэффициент — отношение, а не угол или расстояние. В обеих разностях используйте одинаковый порядок точек.', 'coordinate'],
  ['Undefined gradient', 'Неопределённый угловой коэффициент', 'A vertical line has no finite slope because distinct points on it have Δx = 0, making Δy/Δx undefined.', 'Вертикальная прямая не имеет конечного углового коэффициента: у разных её точек Δx = 0, поэтому Δy/Δx не определено.', 'For (4, 1) and (4, 7), the attempted slope is 6/0; the line is written x = 4.', 'Для (4, 1) и (4, 7) попытка вычислить коэффициент даёт 6/0; уравнение прямой — x = 4.', 'Undefined is not zero. Horizontal lines have slope 0; vertical lines cannot be written y = mx + b with finite m.', '«Не определён» не означает ноль. У горизонтальной прямой коэффициент 0; вертикальную нельзя записать y = mx + b с конечным m.'],
  ['Perpendicular lines', 'Перпендикулярные прямые', 'Two lines in a plane that intersect at a right angle of 90°.', 'Две прямые на плоскости, пересекающиеся под прямым углом 90°.', 'The lines y = 2x and y = −x/2 have slopes with product −1, so they are perpendicular.', 'У прямых y = 2x и y = −x/2 произведение угловых коэффициентов равно −1; поэтому они перпендикулярны.', 'The product rule requires two defined slopes. A vertical line is perpendicular to a horizontal line; use equal axis scales to judge drawn angles.', 'Правило произведения требует двух определённых коэффициентов. Вертикальная и горизонтальная прямые перпендикулярны; на рисунке нужны одинаковые масштабы осей.'],
  ['Negative reciprocal', 'Число, противоположное обратному', 'For a non-zero number m, the value −1/m, obtained by taking its reciprocal and changing the sign.', 'Для ненулевого m это число −1/m: берём обратное число и меняем его знак.', 'For m = −3/4, −1/m = 4/3; their product is −1.', 'Для m = −3/4 имеем −1/m = 4/3; произведение этих чисел равно −1.', 'The reciprocal of −3/4 is −4/3; its negative reciprocal is +4/3. Zero has no reciprocal.', 'Обратное для −3/4 равно −4/3; противоположное обратному равно +4/3. У нуля нет обратного числа.'],
  ['Parallel lines', 'Параллельные прямые', 'Distinct lines in the same plane that have no common point, however far extended.', 'Различные прямые одной плоскости, не имеющие общей точки при любом продолжении.', 'y = 3x + 1 and y = 3x − 5 have the same slope and different intercepts, so they are parallel.', 'У y = 3x + 1 и y = 3x − 5 одинаковый угловой коэффициент и разные пересечения с осью y; прямые параллельны.', 'Equal slope and equal intercept describe the same line, not two distinct parallel lines. Two distinct vertical lines are also parallel.', 'Одинаковые коэффициент и свободный член задают одну и ту же прямую. Две различные вертикальные прямые тоже параллельны.'],
]);
group(['systems', 'ruSystems'], [
  ['Simultaneous equations', 'Система уравнений', 'Equations imposed together: a solution must use the same variable values to satisfy every equation in the system.', 'Уравнения, которые должны выполняться одновременно: решение — один набор значений переменных, удовлетворяющий каждому уравнению.', 'x + y = 7 and x − y = 1 give 2x = 8, hence x = 4, y = 3. Both original equations hold.', 'Из x + y = 7 и x − y = 1 получаем 2x = 8, затем x = 4, y = 3. Обе исходные строки верны.', 'Solving only one equation does not solve the system. Two linear equations can have one, no or infinitely many common solutions.', 'Решить одно уравнение недостаточно. Два линейных уравнения могут иметь одно, ни одного или бесконечно много общих решений.'],
  ['Elimination', 'Метод сложения; исключение переменной', 'Replace an equation by a suitable sum of multiples of the equations so that one variable cancels, while retaining an equivalent system.', 'Заменить одно уравнение подходящей суммой кратных уравнений так, чтобы исключить переменную и сохранить равносильную систему.', 'Add x + y = 7 to x − y = 1: 2x = 8. Then use an original equation to recover y = 3.', 'Складываем x + y = 7 и x − y = 1: 2x = 8. Затем по исходному уравнению находим y = 3.', 'The sum alone loses information; keep another independent equation to recover all unknowns.', 'Одна сумма теряет информацию; сохраняйте ещё одно независимое уравнение для нахождения остальных неизвестных.'],
  ['Substitution method', 'Метод подстановки', 'Solve one equation for a variable, substitute its equal expression into another equation, then recover and check the remaining values.', 'Из одного уравнения выразить переменную, подставить равное ей выражение в другое, затем найти и проверить остальные значения.', 'If y = 7 − x and x − y = 1, then x − (7 − x) = 1, so x = 4 and y = 3.', 'Если y = 7 − x и x − y = 1, то x − (7 − x) = 1, откуда x = 4 и y = 3.', 'Replace the whole expression with brackets when needed. Substitution is valid only where the expression is defined.', 'Подставляйте всё выражение, при необходимости в скобках. Оно должно быть определено при рассматриваемых значениях.'],
]);
group(['setOperations', 'ruSets'], [
  ['Intersection', 'Пересечение', 'The set of elements belonging to both sets. For two graphs, it is the set of points lying on both graphs.', 'Множество элементов, принадлежащих обоим множествам. Для двух графиков это множество точек, лежащих на обоих графиках.', 'If A = {1, 3, 5} and B = {3, 4}, A ∩ B = {3}. Two lines meeting at (4, 3) share that point.', 'Если A = {1, 3, 5}, B = {3, 4}, то A ∩ B = {3}. Две прямые, встречающиеся в (4, 3), имеют эту общую точку.', 'Intersection means “and”; union means “at least one”. The intersection may be empty or contain more than one point.', 'Пересечение означает «и»; объединение — «хотя бы одно». Пересечение может быть пустым или содержать много точек.', 'venn'],
  ['Union', 'Объединение', 'The set containing every element that belongs to at least one of the given sets, counting shared elements once.', 'Множество всех элементов, принадлежащих хотя бы одному из данных множеств; общий элемент входит только один раз.', 'For A = {1, 3, 5}, B = {3, 4}, A ∪ B = {1, 3, 4, 5}.', 'Для A = {1, 3, 5}, B = {3, 4} получаем A ∪ B = {1, 3, 4, 5}.', '“Or” here includes “both”. Adding set sizes double-counts the intersection unless it is subtracted.', '«Или» здесь включает «оба». При сложении мощностей пересечение считают дважды, поэтому его нужно вычесть.', 'venn'],
  ['Complement', 'Дополнение множества', 'Relative to a specified universal set U, the complement of A contains all elements of U that are not in A.', 'Относительно заданного универсального множества U дополнение A состоит из элементов U, не входящих в A.', 'If U = {1, 2, 3, 4} and A = {1, 4}, then A′ = {2, 3}.', 'Если U = {1, 2, 3, 4}, A = {1, 4}, то A′ = {2, 3}.', 'Changing U can change the complement. “Not in A” never means ignoring the specified universe.', 'При изменении U дополнение может измениться. Условие «не входит в A» рассматривают внутри заданного универсального множества.', 'venn'],
  ['Disjoint sets', 'Непересекающиеся множества', 'Sets with no shared elements, so their intersection is the empty set.', 'Множества без общих элементов; их пересечение — пустое множество.', '{1, 3} and {2, 4} are disjoint because no number appears in both.', '{1, 3} и {2, 4} не пересекаются: ни одно число не входит в оба множества.', 'Different sets need not be disjoint: {1, 2} and {2, 3} differ but share 2.', 'Различные множества не обязательно не пересекаются: {1, 2} и {2, 3} различны, но имеют общий элемент 2.'],
]);
group(['sets'], [
  ['Set', 'Множество', 'A collection of distinct objects with an unambiguous rule determining membership.', 'Совокупность различных объектов с однозначно заданной принадлежностью каждого рассматриваемого объекта.', 'A = {2, 4, 6}; listing {6, 2, 4, 2} gives the same set.', 'A = {2, 4, 6}; запись {6, 2, 4, 2} задаёт то же множество.', 'Order and repetitions do not change a set. They can change a list or sequence.', 'Порядок и повторения не меняют множество, но могут менять список или последовательность.'],
  ['Element / member', 'Элемент множества', 'An individual object belonging to a set; the notation a ∈ A asserts that a is an element of A.', 'Отдельный объект, входящий в множество; запись a ∈ A утверждает, что a — элемент A.', 'If A = {2, 4, 6}, then 4 ∈ A and 5 ∉ A.', 'Если A = {2, 4, 6}, то 4 ∈ A и 5 ∉ A.', '4 and {4} are different objects: 4 ∈ A, while {4} ⊆ A.', '4 и {4} — разные объекты: 4 ∈ A, а {4} ⊆ A.'],
  ['Universal set', 'Универсальное множество', 'The set U containing all objects allowed in the current problem; every set under discussion is considered within it.', 'Множество U всех объектов, рассматриваемых в данной задаче; обсуждаемые множества рассматриваются внутри него.', 'If the problem concerns die outcomes, use U = {1, 2, 3, 4, 5, 6}.', 'Для результатов броска обычного кубика берём U = {1, 2, 3, 4, 5, 6}.', 'U depends on the problem; it is not a set of absolutely everything. The Venn rectangle represents this chosen universe.', 'U зависит от задачи и не означает множество абсолютно всего. Прямоугольник диаграммы обозначает выбранную область.', 'venn'],
  ['Empty set', 'Пустое множество', 'The set with no elements, written ∅ or {}.', 'Множество, не содержащее ни одного элемента; обозначается ∅ или {}.', 'The set of integers strictly between 2 and 3 is ∅, so its cardinality is 0.', 'Множество целых чисел строго между 2 и 3 равно ∅; его мощность равна 0.', '∅ is not {0}: the latter contains one element. Also {∅} contains one element, namely the empty set.', '∅ не равно {0}: в последнем один элемент. В {∅} тоже один элемент — само пустое множество.'],
  ['Cardinality', 'Мощность множества', 'For a finite set, the number of distinct elements it contains, written |A| or n(A).', 'Для конечного множества число его различных элементов; обозначается |A| или n(A).', 'For A = {2, 2, 5, 8}, repeated 2 counts once, so n(A) = 3.', 'В A = {2, 2, 5, 8} повторяющуюся 2 считают один раз, поэтому n(A) = 3.', 'Cardinality is a number, while the set is a collection. Here we count finite sets; infinite cardinalities require a broader definition.', 'Мощность — число, множество — совокупность объектов. Здесь считаем конечные множества; бесконечные мощности требуют более общего определения.'],
]);
group(['subsets'], [
  ['Subset', 'Подмножество', 'A set A is a subset of B, written A ⊆ B, when every element of A also belongs to B.', 'Множество A — подмножество B, A ⊆ B, если каждый элемент A принадлежит B.', '{2, 4} ⊆ {2, 4, 6}; also every set is a subset of itself.', '{2, 4} ⊆ {2, 4, 6}; каждое множество также является подмножеством самого себя.', '⊆ allows equality. A proper subset excludes equality; ∈ compares an element with a set, not two sets as subsets.', '⊆ допускает равенство; собственное подмножество его исключает. Символ ∈ обозначает принадлежность элемента, а не включение подмножеств.'],
]);

group(['functions'], [
  ['Function', 'Функция', 'An assignment that gives each input in its domain exactly one output.', 'Соответствие, которое каждому входному значению из области определения ставит в соответствие ровно одно выходное значение.', 'f(x) = x² sends both −2 and 2 to 4; each individual input still has just one output.', 'f(x) = x² сопоставляет и −2, и 2 значение 4; каждому отдельному входу всё равно соответствует один выход.', 'Different inputs may share an output. One input with two different outputs fails the definition.', 'Разные входы могут иметь общий выход. Один вход с двумя различными выходами нарушает определение.', 'function'],
  ['Mapping', 'Отображение', 'An assignment from a source set to a target set. A function mapping assigns exactly one target element to every source element.', 'Соответствие между исходным множеством и целевым множеством. Отображение как функция каждому исходному элементу сопоставляет ровно один целевой.', 'The rule x ↦ 2x + 1 sends 0 ↦ 1 and 3 ↦ 7.', 'Правило x ↦ 2x + 1 даёт 0 ↦ 1 и 3 ↦ 7.', 'An arrow diagram must show the whole stated domain; a few sample arrows do not specify an arbitrary function completely.', 'Диаграмма должна охватывать всю заявленную область. Несколько примеров стрелок не задают произвольную функцию полностью.', 'function'],
  ['Vertical line test', 'Проверка вертикальной прямой', 'A plane graph represents y as a function of x exactly when every vertical line intersects it at most once.', 'График на плоскости задаёт y как функцию x тогда и только тогда, когда любая вертикальная прямая пересекает его не более чем в одной точке.', 'The circle x² + y² = 1 fails: x = 0 meets it at (0, 1) and (0, −1).', 'Окружность x² + y² = 1 не проходит проверку: x = 0 пересекает её в (0, 1) и (0, −1).', 'A line with no intersection corresponds to an x outside the domain. The horizontal line test checks one-to-one behaviour instead.', 'Отсутствие пересечения означает x вне области определения. Горизонтальными прямыми проверяют взаимную однозначность.'],
  ['One-to-one / many-to-one', 'Инъективная функция / функция с совпадающими значениями', 'A one-to-one function never assigns the same output to two different inputs. A many-to-one function does so for at least one pair.', 'У инъективной функции разным входам соответствуют разные выходы. У неинъективной функции хотя бы два разных входа дают один выход.', 'On ℝ, x³ is one-to-one; x² is many-to-one since (−3)² = 3² = 9.', 'На ℝ функция x³ инъективна; x² неинъективна, поскольку (−3)² = 3² = 9.', 'The domain matters: x² becomes one-to-one if restricted to x ≥ 0. Many-to-one still satisfies the function definition.', 'Область важна: x² становится инъективной при ограничении x ≥ 0. Совпадение выходов не нарушает определение функции.', 'function'],
]);
group(['domain', 'ruDomain'], [
  ['Domain', 'Область определения', 'The complete set of inputs on which the specified function is defined, including any restrictions imposed by its context.', 'Все входные значения, на которых заданная функция определена, с учётом ограничений задачи.', 'For f(x) = √(x − 2) over the reals, x − 2 ≥ 0, so the domain is [2, ∞).', 'Для f(x) = √(x − 2) над действительными числами требуется x − 2 ≥ 0; область определения — [2, ∞).', 'A formula alone may have a larger possible domain than a real-world model: a time variable may be restricted to t ≥ 0.', 'Допустимая область формулы может быть шире области модели: например, время может ограничиваться t ≥ 0.', 'function'],
  ['Range', 'Множество значений', 'The set of outputs actually attained by a function as its input runs through the specified domain.', 'Все выходные значения, которые функция действительно принимает на заданной области определения.', 'For f(x) = x² on [−2, 1], the minimum is 0 and maximum is 4, so the range is [0, 4].', 'Для f(x) = x² на [−2, 1] минимум равен 0, максимум — 4; множество значений — [0, 4].', 'Range concerns outputs; domain concerns inputs. Changing the domain can change the range.', 'Множество значений относится к выходам, область определения — к входам. Изменение области может изменить множество значений.', 'function'],
]);
group(['quadratics', 'parabola'], [
  ['Quadratic', 'Квадратичный; квадратный трёхчлен', 'In one variable, a polynomial of degree 2: ax² + bx + c with a ≠ 0. A quadratic function uses this polynomial as its output rule.', 'Для одной переменной многочлен второй степени: ax² + bx + c при a ≠ 0. Квадратичная функция задаёт этим многочленом выход.', '3x² − 2x + 5 is quadratic because the largest non-zero power is 2.', '3x² − 2x + 5 — квадратный трёхчлен, поскольку старшая ненулевая степень равна 2.', 'If a = 0 it is no longer quadratic. Distinguish an expression, the function y = ax² + bx + c, and an equation set equal to zero.', 'При a = 0 выражение уже не квадратично. Различайте многочлен, функцию y = ax² + bx + c и уравнение, где многочлен приравнен нулю.'],
  ['Parabola', 'Парабола', 'A curve consisting of points equally distant from a fixed point (focus) and a fixed line (directrix) not containing the focus. A quadratic graph is a vertically oriented parabola.', 'Кривая из точек, равноудалённых от фиксированной точки (фокуса) и фиксированной прямой (директрисы), не проходящей через фокус. График квадратичной функции — парабола с вертикальной осью.', 'y = (x − 1)² − 2 opens upwards and has vertex (1, −2).', 'y = (x − 1)² − 2 направлена ветвями вверх и имеет вершину (1, −2).', 'Not every U-shaped graph is a parabola: y = x⁴ is not quadratic. A sideways parabola need not define y as a function of x.', 'Не всякая U-образная кривая — парабола: y = x⁴ не квадратична. Парабола с горизонтальной осью может не задавать y как функцию x.', 'quadratic'],
  ['Vertex / turning point', 'Вершина параболы', 'For a quadratic graph y = a(x − h)² + k, the point (h, k) where the graph changes from decreasing to increasing, or vice versa.', 'Для y = a(x − h)² + k точка (h, k), где убывание сменяется возрастанием или наоборот.', 'For y = −2(x + 1)² + 8, the vertex is (−1, 8), a maximum because a < 0.', 'У y = −2(x + 1)² + 8 вершина — (−1, 8); это максимум, поскольку a < 0.', 'A vertex is a point, not only a y-value. Not every turning point on a general curve is a parabola vertex.', 'Вершина — точка, а не только значение y. Не каждая точка поворота произвольной кривой является вершиной параболы.', 'quadratic'],
  ['Axis of symmetry', 'Ось симметрии', 'A line across which reflection leaves a figure unchanged. For y = ax² + bx + c, it is x = −b/(2a).', 'Прямая, отражение относительно которой совмещает фигуру с собой. Для y = ax² + bx + c это x = −b/(2a).', 'For y = (x − 2)² − 3, x = 2 is the symmetry axis; x = 1 and x = 3 give equal outputs.', 'Для y = (x − 2)² − 3 ось симметрии — x = 2; при x = 1 и x = 3 значения равны.', 'Write a line equation x = 2, not the point (2, 0) or the number 2 alone.', 'Записывайте уравнение прямой x = 2, а не точку (2, 0) или только число 2.', 'quadratic'],
]);
group(['zeros'], [
  ['Root / zero', 'Корень уравнения / нуль функции', 'A zero of f is an input r for which f(r) = 0. It is a root of the equation f(x) = 0.', 'Нуль функции f — вход r, при котором f(r) = 0. Это корень уравнения f(x) = 0.', 'f(x) = (x − 2)(x + 4) has zeros 2 and −4; its x-intercepts are (2, 0) and (−4, 0).', 'У f(x) = (x − 2)(x + 4) нули — 2 и −4; точки на оси x — (2, 0) и (−4, 0).', 'A root is an input number; an intercept is a point. A repeated root need not make the graph cross the axis.', 'Корень — входное число, пересечение с осью — точка. При кратном корне график может не переходить через ось.', 'quadratic'],
]);
group(['transformations'], [
  ['Translation / reflection / stretch', 'Сдвиг / отражение / растяжение', 'A translation moves every point by the same vector; a reflection mirrors points in a line; a stretch multiplies distances in a specified direction.', 'Сдвиг перемещает все точки на один вектор; отражение зеркально переносит их относительно прямой; растяжение умножает расстояния в указанном направлении.', 'From y = x² to y = −2(x − 3)² + 1: shift right 3, stretch vertically by 2, reflect in the x-axis, then shift up 1.', 'От y = x² к y = −2(x − 3)² + 1: сдвиг вправо на 3, растяжение по вертикали в 2 раза, отражение относительно оси x, сдвиг вверх на 1.', 'Order can matter. Inside changes affect x: f(x − 3) moves the graph right, not left.', 'Порядок может быть важен. Изменения внутри аргумента относятся к x: f(x − 3) сдвигает график вправо, а не влево.'],
]);
group(['quadraticEquations'], [
  ['Factorise', 'Разложить на множители', 'Rewrite an expression as a product of factors without changing its value on its domain.', 'Представить выражение произведением множителей, не меняя его значения на области определения.', 'x² + x − 6 = (x + 3)(x − 2), since expansion gives x² + 3x − 2x − 6.', 'x² + x − 6 = (x + 3)(x − 2), поскольку раскрытие скобок даёт x² + 3x − 2x − 6.', 'Factorising an expression alone does not find roots; apply the zero-product property only when the product equals zero.', 'Само разложение выражения не находит корни; свойство нулевого произведения применяют, только когда произведение равно нулю.'],
  ['Zero-product property', 'Свойство нулевого произведения', 'For real numbers, a product is zero exactly when at least one of its factors is zero.', 'Произведение действительных чисел равно нулю тогда и только тогда, когда хотя бы один множитель равен нулю.', '(x + 3)(x − 2) = 0 gives x + 3 = 0 or x − 2 = 0, hence x = −3 or 2.', '(x + 3)(x − 2) = 0 даёт x + 3 = 0 или x − 2 = 0, откуда x = −3 или 2.', 'The right side must be zero. From ab = 6 you cannot conclude a = 6 or b = 6.', 'Правая часть должна быть нулевой. Из ab = 6 нельзя заключать a = 6 или b = 6.'],
  ['Complete the square', 'Выделить полный квадрат', 'Rewrite a quadratic as a multiple of a squared linear expression plus a constant.', 'Представить квадратный трёхчлен как кратное квадрата линейного выражения плюс постоянное слагаемое.', 'x² + 6x + 5 = (x + 3)² − 9 + 5 = (x + 3)² − 4.', 'x² + 6x + 5 = (x + 3)² − 9 + 5 = (x + 3)² − 4.', 'Balance the added square by subtracting it; otherwise the value changes. If a ≠ 1, first account for the leading coefficient.', 'Добавленный квадрат нужно компенсировать вычитанием, иначе значение изменится. При a ≠ 1 сначала учтите старший коэффициент.'],
  ['Discriminant', 'Дискриминант', 'For ax² + bx + c = 0 with a ≠ 0, the number D = b² − 4ac determining the number of distinct real roots.', 'Для ax² + bx + c = 0 при a ≠ 0 число D = b² − 4ac, определяющее количество различных действительных корней.', 'For x² + 2x + 5 = 0, D = 4 − 20 = −16, so there are no real roots.', 'Для x² + 2x + 5 = 0: D = 4 − 20 = −16, поэтому действительных корней нет.', 'D > 0 gives two real roots; D = 0 gives one repeated real root; D < 0 still allows two complex roots.', 'При D > 0 два действительных корня; при D = 0 один двукратный; при D < 0 остаются два комплексных корня.'],
]);
group(['sequences'], [
  ['Term / nth term', 'Член последовательности / n-й член', 'A term is one entry in an ordered sequence. The nth term uₙ is the entry at index n under the stated indexing convention.', 'Член — отдельное значение упорядоченной последовательности. n-й член uₙ стоит на позиции n при выбранной нумерации.', 'For uₙ = 4n − 1, n ≥ 1: u₁ = 3, u₂ = 7 and u₅ = 19.', 'Для uₙ = 4n − 1, n ≥ 1: u₁ = 3, u₂ = 7 и u₅ = 19.', 'The index n is the position; uₙ is the value. A sequence term is different from an additive term in an expression.', 'Индекс n — позиция, uₙ — значение. Член последовательности отличается от слагаемого алгебраического выражения.'],
  ['Explicit formula', 'Явная формула', 'A rule giving a sequence term directly from its index, without requiring earlier terms to be computed first.', 'Правило, позволяющее найти член по его номеру без предварительного вычисления предыдущих членов.', 'uₙ = 3 × 2ⁿ⁻¹ gives u₄ = 3 × 8 = 24 directly.', 'uₙ = 3 × 2ⁿ⁻¹ сразу даёт u₄ = 3 × 8 = 24.', 'State the starting index. Changing from n = 1 to n = 0 changes the matching formula.', 'Укажите начальный номер. Переход от нумерации с 1 к нумерации с 0 меняет соответствующую формулу.'],
  ['Recursive formula', 'Рекуррентная формула', 'A rule expressing a term using previous terms, together with enough initial values to determine the sequence.', 'Правило, выражающее член через предыдущие, вместе с достаточными начальными значениями для задания последовательности.', 'u₁ = 3 and uₙ₊₁ = 2uₙ give 3, 6, 12, 24, …', 'u₁ = 3 и uₙ₊₁ = 2uₙ задают 3, 6, 12, 24, …', 'The recurrence alone is incomplete: uₙ₊₁ = 2uₙ gives different sequences for different first terms.', 'Одного рекуррентного правила недостаточно: uₙ₊₁ = 2uₙ при разных первых членах задаёт разные последовательности.'],
]);
group(['arithmetic'], [
  ['Arithmetic / linear sequence', 'Арифметическая прогрессия', 'A sequence in which each term after the first equals the previous term plus the same constant difference d.', 'Последовательность, где каждый член после первого получается прибавлением одной и той же разности d к предыдущему.', '5, 2, −1, −4, … has d = −3 and uₙ = 5 − 3(n − 1), n ≥ 1.', '5, 2, −1, −4, … имеет d = −3 и uₙ = 5 − 3(n − 1), n ≥ 1.', 'Equal differences distinguish arithmetic sequences; equal ratios distinguish geometric sequences. A constant sequence has d = 0.', 'Постоянная разность характеризует арифметическую прогрессию, постоянное отношение — геометрическую. У постоянной последовательности d = 0.'],
]);
group(['geometric'], [
  ['Geometric sequence', 'Геометрическая прогрессия', 'A sequence formed by multiplying each preceding term by a fixed ratio r; uₙ = arⁿ⁻¹ when the first term is a.', 'Последовательность, где следующий член получают умножением предыдущего на постоянный знаменатель r; при первом члене a имеем uₙ = arⁿ⁻¹.', '8, −4, 2, −1, … has common ratio −1/2, so u₅ = 1/2.', '8, −4, 2, −1, … имеет знаменатель −1/2, поэтому u₅ = 1/2.', 'The ratio can be negative. Computing it by division requires a non-zero preceding term; conventions may exclude zero terms.', 'Знаменатель может быть отрицательным. Для вычисления отношения делением нужен ненулевой предыдущий член; соглашение может исключать нулевые члены.'],
]);
group(['series'], [
  ['Convergence', 'Сходимость', 'Approach to a finite limit: eventually values stay arbitrarily close to it. An infinite series converges when its partial sums do.', 'Приближение к конечному пределу: начиная с некоторого момента значения остаются сколь угодно близкими к нему. Ряд сходится, если сходятся его частичные суммы.', 'For 1 + 1/2 + 1/4 + …, the first n terms sum to 2(1 − 2⁻ⁿ), tending to 2.', 'Для 1 + 1/2 + 1/4 + … сумма первых n членов равна 2(1 − 2⁻ⁿ) и стремится к 2.', 'Terms tending to zero do not alone guarantee a convergent series. A geometric series with non-zero first term converges exactly when |r| < 1.', 'Стремление членов к нулю само по себе не гарантирует сходимость ряда. Геометрический ряд с ненулевым первым членом сходится тогда и только тогда, когда |r| < 1.'],
]);

group(['rightTriangles'], [
  ['Hypotenuse', 'Гипотенуза', 'The side opposite the 90° angle in a right triangle; it is longer than either of the other two sides.', 'Сторона прямоугольного треугольника, лежащая напротив угла 90°; она длиннее каждого из двух катетов.', 'With legs 6 and 8, the hypotenuse c satisfies c² = 6² + 8² = 100, so c = 10.', 'При катетах 6 и 8 гипотенуза c удовлетворяет c² = 6² + 8² = 100, откуда c = 10.', 'Only a right triangle has a hypotenuse. Its identity does not change when you choose the other acute reference angle.', 'Гипотенуза есть только у прямоугольного треугольника. Выбор другого острого угла не меняет её.', 'triangle'],
  ['Opposite / adjacent', 'Противолежащий / прилежащий катет', 'Relative to a chosen acute angle in a right triangle, the opposite leg faces that angle; the adjacent leg touches it and is not the hypotenuse.', 'Относительно выбранного острого угла прямоугольного треугольника противолежащий катет лежит напротив, а прилежащий образует этот угол вместе с гипотенузой.', 'If opposite = 6 and adjacent = 8, tan θ = 6/8 = 3/4.', 'Если противолежащий катет равен 6, прилежащий — 8, то tan θ = 6/8 = 3/4.', 'Changing the reference angle swaps the two legs’ roles. The hypotenuse is never the adjacent leg in these ratios.', 'При смене острого угла роли катетов меняются. Гипотенуза не является прилежащим катетом в этих отношениях.', 'triangle'],
]);
group(['cosine', 'bearing'], [
  ['Bearing', 'Азимут', 'A direction angle measured clockwise from north at the starting point, conventionally from 000° up to but not including 360°.', 'Угол направления, отсчитываемый по часовой стрелке от севера в начальной точке, обычно от 000° включительно до 360° не включительно.', 'A point 6 km east and 8 km north has bearing arctan(6/8) ≈ 36.87°, written 037° to the nearest degree.', 'Точка в 6 км к востоку и 8 км к северу имеет азимут arctan(6/8) ≈ 36,87°, после округления 037°.', 'The reference is north, not the positive x-axis. Reverse bearings differ by 180° in the plane model with parallel north lines.', 'Отсчёт ведётся от севера, а не от положительной оси x. В плоской модели с параллельными направлениями севера обратные азимуты отличаются на 180°.'],
  ['Cosine rule', 'Теорема косинусов', 'In any non-degenerate Euclidean triangle, c² = a² + b² − 2ab cos C, where C is the angle between sides a and b.', 'В любом невырожденном евклидовом треугольнике c² = a² + b² − 2ab cos C, где C — угол между сторонами a и b.', 'For a = 5, b = 7, C = 60°: c² = 25 + 49 − 70 × 1/2 = 39, so c = √39.', 'При a = 5, b = 7, C = 60°: c² = 25 + 49 − 70 × 1/2 = 39, поэтому c = √39.', 'C is opposite the side c you are finding. At C = 90° the cosine term vanishes, giving Pythagoras.', 'Угол C лежит напротив искомой стороны c. При C = 90° косинусный член исчезает, и получается теорема Пифагора.'],
]);
group(['inverseTrig'], [
  ['Inverse trigonometric function', 'Обратная тригонометрическая функция', 'A function recovering a principal angle from a trigonometric ratio after restricting the original trig function to a one-to-one domain.', 'Функция, возвращающая главное значение угла по тригонометрическому отношению после ограничения исходной функции до взаимно однозначной области.', 'In degree mode, arcsin(1/2) = 30°. Solving sin θ = 1/2 on [0°, 180°] also requires 150°.', 'В градусном режиме arcsin(1/2) = 30°. Но у sin θ = 1/2 на [0°, 180°] есть также решение 150°.', 'sin⁻¹ here means arcsin, not 1/sin. Principal ranges: arcsin [−90°, 90°], arccos [0°, 180°], arctan (−90°, 90°).', 'sin⁻¹ здесь означает arcsin, а не 1/sin. Главные значения: arcsin [−90°, 90°], arccos [0°, 180°], arctan (−90°, 90°).'],
]);
group(['sine'], [
  ['Sine rule', 'Теорема синусов', 'In any non-degenerate Euclidean triangle, each side divided by the sine of its opposite angle has the same value: a/sin A = b/sin B = c/sin C.', 'В любом невырожденном евклидовом треугольнике отношение стороны к синусу противолежащего угла одинаково: a/sin A = b/sin B = c/sin C.', 'If a = 6, A = 30°, B = 45°, then b = 6 sin 45°/sin 30° = 6√2.', 'При a = 6, A = 30°, B = 45° имеем b = 6 sin 45°/sin 30° = 6√2.', 'Always match opposite pairs. An inverse-sine calculation may miss a supplementary angle; check whether a second triangle fits.', 'Сопоставляйте противоположные пары. Вычисление arcsin может пропустить дополнительный угол; проверяйте возможность второго треугольника.'],
  ['Included angle', 'Угол между заданными сторонами', 'The angle formed where two specified sides of a triangle meet.', 'Угол, образованный двумя указанными сторонами треугольника в их общей вершине.', 'If sides a = 4 and b = 7 enclose C = 30°, the area is ½ab sin C = 7 square units.', 'Если стороны a = 4 и b = 7 образуют C = 30°, площадь равна ½ab sin C = 7 квадратных единиц.', 'In ½ab sin C, C must lie between a and b. An angle opposite either of them cannot be substituted without changing the pair.', 'В ½ab sin C угол C должен находиться между a и b. Нельзя подставлять угол напротив одной из них, не изменив пару сторон.'],
]);
group(['waves'], [
  ['Amplitude', 'Амплитуда', 'For a sine or cosine wave, the maximum vertical distance from the midline; it is half the difference between maximum and minimum values.', 'Для синусоиды или косинусоиды максимальное отклонение по вертикали от средней линии; половина разности максимума и минимума.', 'For y = −3 sin x + 2, the range is [−1, 5], midline y = 2 and amplitude (5 − (−1))/2 = 3.', 'Для y = −3 sin x + 2 множество значений [−1, 5], средняя линия y = 2, амплитуда (5 − (−1))/2 = 3.', 'Amplitude is non-negative: |A|, not A. A vertical shift changes the midline, not the amplitude. Tangent has no finite amplitude.', 'Амплитуда неотрицательна: |A|, а не A. Вертикальный сдвиг меняет среднюю линию, но не амплитуду. У тангенса нет конечной амплитуды.'],
  ['Period', 'Период', 'A positive input shift T for which f(x + T) = f(x) throughout the domain. The fundamental period is the smallest such positive shift, when it exists.', 'Положительное смещение аргумента T, при котором f(x + T) = f(x) во всей области. Наименьший положительный период, если он существует, — основной.', 'For y = sin(3x) in degrees, the fundamental period is 360°/3 = 120°.', 'Для y = sin(3x) в градусах основной период равен 360°/3 = 120°.', 'Use the input’s units: sine’s fundamental period is 360° or 2π radians. Larger integer multiples are also periods.', 'Учитывайте единицы аргумента: основной период синуса 360° или 2π радиан. Положительные целые кратные тоже являются периодами.'],
]);
group(['circles'], [
  ['Chord / diameter', 'Хорда / диаметр', 'A chord is a segment whose endpoints lie on a circle. A diameter is a chord passing through the centre.', 'Хорда — отрезок с концами на окружности. Диаметр — хорда, проходящая через центр.', 'If the radius is 5 cm, each diameter is 10 cm; a chord not through the centre is shorter.', 'Если радиус равен 5 см, каждый диаметр равен 10 см; хорда, не проходящая через центр, короче.', 'A chord is straight; an arc follows the circumference. Every diameter is a chord, but not every chord is a diameter.', 'Хорда прямолинейна; дуга идёт по окружности. Каждый диаметр — хорда, но не каждая хорда — диаметр.', 'circle'],
  ['Tangent', 'Касательная к окружности', 'A straight line in the circle’s plane having exactly one common point with the circle; it is perpendicular to the radius at that point.', 'Прямая в плоскости окружности, имеющая с ней ровно одну общую точку; она перпендикулярна радиусу в этой точке.', 'For x² + y² = 25, the line x = 5 is tangent at (5, 0).', 'Для x² + y² = 25 прямая x = 5 касается окружности в (5, 0).', 'This one-contact-point definition is specific to a circle. A tangent to a general curve can cross that curve elsewhere.', 'Определение через одну общую точку относится к окружности. Касательная к произвольной кривой может пересекать её в других местах.'],
  ['Arc', 'Дуга окружности', 'A connected part of a circle’s circumference between two endpoints; specifying the chosen arc distinguishes minor and major arcs.', 'Связная часть окружности между двумя концами; нужно уточнять выбранную дугу, различая меньшую и большую.', 'For radius 6 cm and central angle 60°, the minor arc length is (60/360) × 2π × 6 = 2π cm.', 'При радиусе 6 см и центральном угле 60° длина меньшей дуги (60/360) × 2π × 6 = 2π см.', 'Arc length is a length. Its degree measure is the associated central angle, not a length or area.', 'Длина дуги — величина длины. Её градусная мера — соответствующий центральный угол, а не длина или площадь.', 'circle'],
  ['Sector', 'Круговой сектор', 'A region of a disk bounded by two radii and the arc joining their endpoints.', 'Часть круга, ограниченная двумя радиусами и соединяющей их концы дугой.', 'With r = 6 cm and θ = 60°, sector area = (60/360)π × 6² = 6π cm².', 'При r = 6 см и θ = 60° площадь сектора равна (60/360)π × 6² = 6π см².', 'A sector uses two radii. A circular segment uses a chord and an arc. State which arc is used: minor or major.', 'Сектор ограничивают два радиуса. Сегмент ограничивают хорда и дуга. Уточняйте, выбрана меньшая или большая дуга.', 'circle'],
  ['Segment', 'Круговой сегмент', 'A region of a disk bounded by a chord and one of the arcs joining the chord’s endpoints.', 'Часть круга, ограниченная хордой и одной из дуг между концами этой хорды.', 'For r = 6 cm and minor central angle 60°, segment area = sector − triangle = 6π − 9√3 cm².', 'При r = 6 см и меньшем центральном угле 60° площадь сегмента = сектор − треугольник = 6π − 9√3 см².', 'Here “segment” is a two-dimensional circle region; “line segment” means a straight interval between points. Sector-minus-triangle applies to the minor segment for 0° < θ ≤ 180°.', 'Здесь segment — двумерная часть круга; line segment — отрезок прямой. Формула «сектор минус треугольник» относится к меньшему сегменту при 0° < θ ≤ 180°.', 'circle'],
  ['Cyclic quadrilateral', 'Вписанный четырёхугольник', 'A quadrilateral whose four vertices all lie on a single circle.', 'Четырёхугольник, все четыре вершины которого лежат на одной окружности.', 'If a convex cyclic quadrilateral has one interior angle 112°, its opposite angle is 180° − 112° = 68°.', 'Если внутренний угол выпуклого вписанного четырёхугольника равен 112°, противоположный равен 180° − 112° = 68°.', 'For a convex cyclic quadrilateral opposite angles are supplementary. Adjacent angles need not sum to 180°.', 'У выпуклого вписанного четырёхугольника сумма противоположных углов 180°. Соседние углы не обязаны давать 180°.'],
]);
group(['rationalExpressions', 'ruDomain'], [
  ['Algebraic fraction', 'Алгебраическая дробь', 'A quotient of algebraic expressions, defined only when its denominator is non-zero. In this course, rational expressions use polynomial numerators and denominators.', 'Частное алгебраических выражений, определённое только при ненулевом знаменателе. В этом курсе рациональные дроби имеют многочлены в числителе и знаменателе.', '(x + 1)/(x − 2) is defined for x ≠ 2. At x = 5 its value is 6/3 = 2.', '(x + 1)/(x − 2) определена при x ≠ 2. При x = 5 её значение равно 6/3 = 2.', 'The entire numerator is divided by the entire denominator. (x + 1)/x does not simplify to 1 + 1.', 'Весь числитель делится на весь знаменатель. (x + 1)/x не сокращается до 1 + 1.'],
  ['Rational equation', 'Рациональное уравнение', 'An equation built from rational expressions (ratios of polynomials), solved only on the domain of the original expressions.', 'Уравнение с рациональными выражениями — отношениями многочленов; решается на области допустимых значений исходных выражений.', 'For 1/(x − 1) = 2, first exclude x = 1; then 1 = 2x − 2 gives x = 3/2, which checks.', 'Для 1/(x − 1) = 2 сначала исключаем x = 1; затем 1 = 2x − 2 даёт x = 3/2; проверка подтверждает корень.', 'Clearing denominators can conceal restrictions. A candidate making an original denominator zero is never a solution.', 'Умножение на знаменатели может скрыть ограничения. Кандидат, обращающий исходный знаменатель в ноль, не является решением.'],
  ['Excluded value', 'Недопустимое значение', 'A value outside the original domain, so the expression or equation cannot be evaluated there.', 'Значение вне исходной области допустимых значений, при котором выражение или уравнение не имеет смысла.', '(x² − 4)/(x − 2) = x + 2 only for x ≠ 2. Cancelling x − 2 does not restore x = 2.', '(x² − 4)/(x − 2) = x + 2 только при x ≠ 2. Сокращение x − 2 не делает x = 2 допустимым.', 'Restrictions come from the original expression. An excluded denominator zero may create a hole, not necessarily an asymptote.', 'Ограничения определяют по исходному выражению. Нуль знаменателя может давать выколотую точку, а не обязательно асимптоту.'],
]);
group(['variation'], [
  ['Direct proportion', 'Прямая пропорциональность', 'A relationship y = kx with fixed k, so equal scaling of x gives equal scaling of y; y is directly proportional to the specified input quantity.', 'Зависимость y = kx при постоянном k: увеличение x в некоторое число раз так же изменяет y. Нужно уточнять, какой величине пропорционален y.', 'If y = 3x, doubling x doubles y. If y is proportional to x², write y = kx² instead.', 'Если y = 3x, удвоение x удваивает y. Если y пропорционален x², нужно писать y = kx².', 'y = 3x + 2 is linear but not directly proportional to x. With x ≠ 0 the ratio y/x stays k.', 'y = 3x + 2 линейна, но не является прямой пропорциональностью x. При x ≠ 0 отношение y/x постоянно и равно k.'],
  ['Inverse proportion', 'Обратная пропорциональность', 'A relationship y = k/x for fixed non-zero k and x ≠ 0; equivalently the product xy stays constant.', 'Зависимость y = k/x при постоянном ненулевом k и x ≠ 0; произведение xy остаётся постоянным.', 'If xy = 24, then x = 4 gives y = 6 and x = 8 gives y = 3.', 'Если xy = 24, то при x = 4 имеем y = 6, а при x = 8 — y = 3.', 'A decreasing graph alone is not evidence of inverse proportion. For positive quantities, doubling x halves y.', 'Одного убывания графика недостаточно для обратной пропорциональности. Для положительных величин удвоение x уменьшает y вдвое.'],
  ['Constant of proportionality', 'Коэффициент пропорциональности', 'The fixed number k defining a specified proportional relationship, such as y = kx or y = k/x.', 'Постоянное число k, задающее выбранную пропорциональную зависимость, например y = kx или y = k/x.', 'If y = kx² and y = 20 when x = 2, then k = 20/4 = 5.', 'Если y = kx² и при x = 2 имеем y = 20, то k = 20/4 = 5.', 'Find k from the stated model: divide by x for y = kx, but multiply by x for y = k/x. Units depend on the model.', 'Находите k по конкретной модели: для y = kx делите на x, а для y = k/x умножайте на x. Единицы k зависят от модели.'],
]);
group(['rationalFunctions'], [
  ['Asymptote', 'Асимптота', 'A line approached by a graph in a specified limiting direction. Vertical asymptotes correspond to unbounded outputs near an input; horizontal ones describe limiting outputs at infinity.', 'Прямая, к которой график приближается при указанном предельном переходе. Вертикальная асимптота связана с неограниченным ростом модуля выхода; горизонтальная — с пределом на бесконечности.', 'For y = 1/(x − 2) + 3, x = 2 is vertical and y = 3 is horizontal.', 'У y = 1/(x − 2) + 3 вертикальная асимптота x = 2, горизонтальная — y = 3.', 'A graph may cross a horizontal asymptote. A cancelled denominator factor can produce a hole rather than a vertical asymptote.', 'График может пересекать горизонтальную асимптоту. Сокращённый множитель знаменателя может давать выколотую точку вместо вертикальной асимптоты.'],
  ['Rational function', 'Рациональная функция', 'A function expressible as P(x)/Q(x), where P and Q are polynomials and inputs with Q(x) = 0 are excluded.', 'Функция вида P(x)/Q(x), где P и Q — многочлены; значения с Q(x) = 0 исключены.', 'f(x) = (x² − 1)/(x − 1) equals x + 1 for x ≠ 1 and has a hole at (1, 2).', 'f(x) = (x² − 1)/(x − 1) равна x + 1 при x ≠ 1 и имеет выколотую точку (1, 2).', 'Not every algebraic fraction is rational: √x/x is not a ratio of polynomials. A polynomial itself is rational with denominator 1.', 'Не всякая алгебраическая дробь рациональна: √x/x не является отношением многочленов. Сам многочлен рационален со знаменателем 1.'],
]);
group(['exponential'], [
  ['Exponential function', 'Показательная функция', 'A function with variable in an exponent and fixed positive base other than 1; the basic form is f(x) = bˣ, b > 0, b ≠ 1.', 'Функция с переменной в показателе и постоянным положительным основанием, отличным от 1; основной вид f(x) = bˣ, b > 0, b ≠ 1.', 'For f(x) = 2ˣ, inputs 0, 1, 2 give 1, 2, 4; each increase of 1 multiplies the output by 2.', 'Для f(x) = 2ˣ входы 0, 1, 2 дают 1, 2, 4; увеличение входа на 1 умножает выход на 2.', '2ˣ is exponential; x² is a power function. Exponential change multiplies by a constant factor over equal input steps, not adds a constant.', '2ˣ — показательная функция, x² — степенная. При одинаковых шагах аргумента выход умножается на постоянный множитель, а не увеличивается на постоянную разность.'],
]);
group(['optimisation'], [
  ['Linear programming', 'Линейное программирование', 'Finding the largest or smallest value of a linear objective function among choices satisfying all linear equality or inequality constraints.', 'Поиск наибольшего или наименьшего значения линейной целевой функции среди вариантов, удовлетворяющих всем линейным равенствам и неравенствам-ограничениям.', 'Maximise P = 3x + 2y with x ≥ 0, y ≥ 0, x ≤ 4, x + y ≤ 6: the maximum is 16 at (4, 2).', 'Максимизируем P = 3x + 2y при x ≥ 0, y ≥ 0, x ≤ 4, x + y ≤ 6: максимум 16 достигается в (4, 2).', 'A model may have no feasible points or no finite optimum. Requiring integer choices adds an integer-programming restriction.', 'В модели может не быть допустимых точек или конечного оптимума. Требование целочисленных значений добавляет условие целочисленного программирования.', 'optimisation'],
  ['Constraint', 'Ограничение', 'A condition that every allowed choice of decision variables must satisfy.', 'Условие, которому обязан удовлетворять каждый допустимый набор значений переменных задачи.', 'x + y ≤ 6 limits the total to 6; x ≥ 0 and y ≥ 0 prohibit negative quantities.', 'x + y ≤ 6 ограничивает сумму шестью; x ≥ 0 и y ≥ 0 исключают отрицательные количества.', 'A constraint determines what is allowed; the objective determines which allowed choice is best.', 'Ограничение определяет допустимость, а целевая функция — какой допустимый выбор лучше.', 'optimisation'],
  ['Feasible region', 'Допустимая область', 'The set of all points satisfying every constraint simultaneously, including domain and sign restrictions.', 'Множество всех точек, одновременно удовлетворяющих каждому ограничению, включая условия на область и знаки.', 'For x ≥ 0, y ≥ 0, x ≤ 4, x + y ≤ 6, the vertices are (0, 0), (4, 0), (4, 2), (0, 6).', 'При x ≥ 0, y ≥ 0, x ≤ 4, x + y ≤ 6 вершины области — (0, 0), (4, 0), (4, 2), (0, 6).', 'This is the intersection of allowed regions, not their union. Boundary lines belong only for inclusive constraints.', 'Это пересечение допустимых областей, а не объединение. Граничные прямые включаются только при нестрогих ограничениях.', 'optimisation'],
  ['Objective function', 'Целевая функция', 'The rule assigning a numerical value to each choice, whose value is to be maximised or minimised.', 'Правило, сопоставляющее каждому выбору числовое значение, которое требуется максимизировать или минимизировать.', 'P(x, y) = 3x + 2y is the objective. At (4, 2), P = 3 × 4 + 2 × 2 = 16.', 'P(x, y) = 3x + 2y — целевая функция. В (4, 2) получаем P = 3 × 4 + 2 × 2 = 16.', 'The function P is the rule; 16 is an objective value; (4, 2) is a choice of variables. These are different objects.', 'Функция P — правило; 16 — значение целевой функции; (4, 2) — набор переменных. Это разные объекты.', 'optimisation'],
  ['Optimal solution', 'Оптимальное решение', 'A feasible choice attaining the best objective value over the entire feasible set.', 'Допустимый набор значений переменных, на котором достигается лучшее значение целевой функции во всей допустимой области.', 'For P = 3x + 2y on the illustrated region, (4, 2) is the optimal solution and 16 is the maximum value.', 'Для P = 3x + 2y на показанной области (4, 2) — оптимальное решение, а 16 — максимальное значение.', 'A feasible point need not be optimal. Several points can tie; an unbounded objective may have no optimal solution.', 'Допустимая точка не обязательно оптимальна. Несколько точек могут дать одинаковый оптимум; неограниченная целевая функция может не иметь оптимального решения.', 'optimisation'],
]);
group(['signs', 'ruSigns'], [
  ['Critical value', 'Граничное значение для метода интервалов', 'In sign analysis here, an input where the expression is zero or undefined, dividing the domain into intervals to examine.', 'В используемом здесь методе интервалов значение, где выражение равно нулю или не определено; такие точки разделяют прямую на исследуемые интервалы.', 'For (x − 1)/(x + 2), mark −2 (undefined) and 1 (zero), then test the three intervals.', 'Для (x − 1)/(x + 2) отмечаем −2 (не определено) и 1 (нуль), затем проверяем три интервала.', 'This is sign-chart terminology, not the derivative-based meaning in calculus. The sign need not change across a repeated root.', 'Это термин для метода интервалов, а не определение критической точки через производную. При кратном корне знак может не меняться.'],
  ['Sign chart', 'Таблица знаков; метод интервалов', 'A diagram or table recording where an expression and its factors are positive, negative, zero or undefined.', 'Схема или таблица, показывающая, где выражение и его множители положительны, отрицательны, равны нулю или не определены.', 'For (x − 1)/(x + 2), signs from left to right are +, −, + on (−∞, −2), (−2, 1), (1, ∞).', 'Для (x − 1)/(x + 2) знаки слева направо: +, −, + на (−∞, −2), (−2, 1), (1, ∞).', 'Testing one point works only after all zeros and discontinuities have split intervals where the sign cannot change.', 'Одна пробная точка достаточна только после выделения всех нулей и разрывов, разделяющих интервалы постоянного знака.'],
  ['Boundary inclusion', 'Включение границы в решение', 'The decision whether a boundary value belongs to the solution set, determined from the original comparison and domain.', 'Решение о том, входит ли граничное значение в множество решений, по исходному знаку сравнения и области допустимых значений.', 'For (x − 1)/(x + 2) ≥ 0, include x = 1 because the value is 0; exclude x = −2 because division by zero is undefined.', 'Для (x − 1)/(x + 2) ≥ 0 включаем x = 1, где значение 0; исключаем x = −2, где возникает деление на ноль.', '≥ or ≤ does not make every boundary valid. Infinity is never an included endpoint.', 'Знаки ≥ и ≤ не делают допустимой любую границу. Бесконечность никогда не является включённым концом промежутка.'],
]);

const modelNotes: Record<string, { en: string; ru: string }> = {
  Fraction: { en: 'The shaded strip assumes equal parts of the same whole. Division extends the idea beyond that picture.', ru: 'Полоска предполагает равные доли одного целого. Определение через деление шире этой картинки.' },
  Bearing: { en: 'These exercises use a flat map with parallel north lines; routes on a curved Earth require additional navigation conventions.', ru: 'Здесь используется плоская карта с параллельными направлениями севера; на сферической Земле нужны дополнительные навигационные соглашения.' },
  'Linear programming': { en: 'The diagram allows real-valued choices. If items must be whole numbers, state and check the integer restriction separately.', ru: 'Диаграмма допускает действительные значения. Если количество предметов должно быть целым, это ограничение задают и проверяют отдельно.' },
  'Feasible region': { en: 'The drawn example is bounded. Other systems can give an empty or unbounded feasible set.', ru: 'Показанная область ограничена. Другая система может задавать пустую или неограниченную область.' },
  Period: { en: 'For A sin(Bx) + D, the formula 360°/|B| is the fundamental period only when A ≠ 0 and B ≠ 0, with x measured in degrees.', ru: 'Для A sin(Bx) + D формула 360°/|B| даёт основной период только при A ≠ 0 и B ≠ 0, если x измеряется в градусах.' },
  'Direct proportion': { en: 'A real-world proportional model assumes a fixed ratio on a stated range; measurement error or changing conditions can break that assumption.', ru: 'Модель реальной пропорциональности предполагает постоянное отношение на указанном диапазоне; погрешности и изменение условий могут нарушать это предположение.' },
  'Exponential function': { en: 'A growth model assumes a fixed multiplier over equal input steps. A few observations do not establish that it remains valid indefinitely.', ru: 'Модель роста предполагает постоянный множитель при равных шагах аргумента. Несколько наблюдений не доказывают её применимость на неограниченное время.' },
};
for (const [term, model] of Object.entries(modelNotes)) if (reviewedTerms[term]) reviewedTerms[term].review.model = model;

export function defineTerm(term: string): Term {
  const value = reviewedTerms[term];
  if (!value) throw new Error(`Missing reviewed mathematics definition: ${term}`);
  return value;
}
