import type { DefinitionSource } from '../../components/content/definitionReview';

const os = (book: string, section: string, title: string): DefinitionSource => ({ title: `OpenStax · ${title}`, url: `https://openstax.org/books/${book}/pages/${section}`, language: 'en', section: title });
const ca = (section: string, title: string) => os('college-algebra-2e', section, title);
const at = (section: string, title: string) => os('algebra-and-trigonometry-2e', section, title);
const ru = (slug: string, title: string): DefinitionSource => ({ title: `Фоксфорд · ${title}`, url: `https://foxford.ru/wiki/matematika/${slug}`, language: 'ru', section: title });
export const definitionSources: Record<string, DefinitionSource> = {
  language: os('elementary-algebra-2e', '1-2-use-the-language-of-algebra', '1.2 · Variables, expressions, equations; identify and combine like terms'),
  distributive: os('elementary-algebra-2e', '1-9-properties-of-real-numbers', '1.9 · Simplify expressions using the distributive property'),
  fractions: os('prealgebra-2e', '4-1-visualize-fractions', '4.1 · Model fractions; numerator and denominator'),
  integers: os('prealgebra-2e', '3-1-introduction-to-integers', '3.1 · Integers and the number line'),
  proof: { title: 'Oscar Levin · Discrete Mathematics: An Open Introduction', url: 'https://discrete.openmathbooks.org/dmoi3/sec_logic-proofs.html', language: 'en', section: '3.2 · Direct proof; proof by (counter) example' },
  statements: { title: 'Oscar Levin · Mathematical Statements', url: 'https://discrete.openmathbooks.org/dmoi3/sec_intro-statements.html', language: 'en', section: '0.2 · Predicates and quantifiers' },
  coordinates: ca('2-1-the-rectangular-coordinate-systems-and-graphs', '2.1 · Coordinates, intercepts, distance and midpoint'),
  lines: ca('4-1-linear-functions', '4.1 · Slope; parallel and perpendicular lines'),
  equations: ca('2-2-linear-equations-in-one-variable', '2.2 · Linear equations; equivalent equations'),
  systems: ca('7-1-systems-of-linear-equations-two-variables', '7.1 · Substitution and addition methods; solution of a system'),
  inequalities: ca('2-7-linear-inequalities-and-absolute-value-inequalities', '2.7 · Linear and compound inequalities; interval notation'),
  sets: os('contemporary-mathematics', '1-1-basic-set-concepts', '1.1 · Sets, elements, empty set and cardinality'),
  subsets: os('contemporary-mathematics', '1-2-subsets', '1.2 · Subsets and proper subsets'),
  setOperations: os('contemporary-mathematics', '1-4-set-operations-with-two-sets', '1.4 · Union, intersection, complement and disjoint sets'),
  functions: ca('3-1-functions-and-function-notation', '3.1 · Functions, mappings and vertical line test'),
  domain: ca('3-2-domain-and-range', '3.2 · Domain and range'),
  transformations: ca('3-5-transformation-of-functions', '3.5 · Shifts, reflections and stretches'),
  quadratics: ca('5-1-quadratic-functions', '5.1 · Quadratic forms, vertex and symmetry'),
  quadraticEquations: ca('2-5-quadratic-equations', '2.5 · Factoring, completing the square and discriminant'),
  zeros: ca('5-5-zeros-of-polynomial-functions', '5.5 · Zeros of polynomial functions'),
  sequences: ca('9-1-sequences-and-their-notations', '9.1 · Explicit and recursive sequence definitions'),
  arithmetic: ca('9-2-arithmetic-sequences', '9.2 · Common difference and nth term'),
  geometric: ca('9-3-geometric-sequences', '9.3 · Common ratio and nth term'),
  series: ca('9-4-series-and-their-notations', '9.4 · Infinite geometric series and convergence'),
  seriesConvergence: os('calculus-volume-2', '5-2-infinite-series', '5.2 · Convergence of partial sums; the divergent harmonic series'),
  rightTriangles: at('7-2-right-triangle-trigonometry', '7.2 · Opposite, adjacent and hypotenuse; right-triangle ratios'),
  inverseTrig: at('8-3-inverse-trigonometric-functions', '8.3 · Restricted domains and inverse trigonometric functions'),
  sine: at('10-1-non-right-triangles-law-of-sines', '10.1 · Law of sines; ambiguous case; triangle area'),
  cosine: at('10-2-non-right-triangles-law-of-cosines', '10.2 · Law of cosines; applied problems'),
  waves: at('8-1-graphs-of-the-sine-and-cosine-functions', '8.1 · Amplitude, midline and period'),
  circles: { title: 'AMSI · Circle Geometry · TIMES teacher module 26', url: 'https://amsi.org.au/teacher_modules/Circle_Geometry.html', language: 'en', section: 'Radii and chords; Arcs and sectors; Segments; Cyclic quadrilaterals; Tangents to circles' },
  parabola: ca('8-3-the-parabola', '8.3 · Focus–directrix definition of a parabola'),
  bearing: { title: 'AMSI · Introductory Trigonometry · TIMES teacher module 23', url: 'https://amsi.org.au/teacher_modules/Introductory_trigonometry.html', language: 'en', section: 'True Bearings; Compass Bearings' },
  rationalExpressions: os('intermediate-algebra-2e', '7-1-multiply-and-divide-rational-expressions', '7.1 · Rational expressions; excluded values and cancelling factors'),
  rationalEquations: os('intermediate-algebra-2e', '7-4-solve-rational-equations', '7.4 · Rational equations; clearing denominators and extraneous solutions'),
  rationalFunctions: ca('5-6-rational-functions', '5.6 · Rational functions, domains and asymptotes'),
  variation: ca('5-8-modeling-using-variation', '5.8 · Direct and inverse variation'),
  exponential: ca('6-1-exponential-functions', '6.1 · Exponential functions, growth and decay'),
  optimisation: { title: 'MIT · Michel Goemans · Linear programming', url: 'https://math.mit.edu/~goemans/18310S15/lpnotes310.pdf#page=1', language: 'en', section: '1 Basics (pp. 1–3): objective, constraints, feasible and optimal solutions' },
  signs: os('intermediate-algebra-2e', '7-6-solve-rational-inequalities', '7.6 · Zero and undefined partition values; sign charts and endpoint inclusion'),
  ruFractions: ru('drobi', 'Дроби · числитель, знаменатель; отличие дроби от доли'),
  ruExpressions: ru('algebraicheskie-vyrazheniya', 'Алгебраические выражения · Что такое алгебраические выражения'),
  ruEquation: ru('ponyatiye-uravneniya', 'Понятие уравнения · определения уравнения и корня'),
  ruSystems: ru('sistemy-dvuh-lineynyh-uravneniy-s-dvumya-neizvestnymi', 'Системы двух линейных уравнений с двумя неизвестными · определение решения системы'),
  ruSets: ru('operatsii-nad-mnozhestvami', 'Операции над множествами · пересечение, объединение и разность'),
  ruDomain: ru('oblast-dopustimyh-znacheniy-ratsionalnyh-vyrazheniy', 'Область допустимых значений рациональных выражений · определение ОДЗ'),
  ruSigns: ru('metod-intervalov', 'Метод интервалов · определение; интервалы постоянного знака'),
  ruInequality: ru('chislovyye-neravenstva-ikh-svoystva', 'Числовые неравенства и их свойства · свойства преобразований'),
};
