import { b, s, type Lesson } from './types';

export const caseLessons: Lesson[] = [
  {
    id: 'chile',
    title: b('Chile: the Maule earthquake, 2010', 'Чили: землетрясение Мауле, 2010'),
    checklist: [7],
    visual: 'subduction',
    intro: b(
      'The checklist names Chile without specifying a year. This lesson uses the widely studied 27 February 2010 Maule earthquake. Learn a connected explanation: plate movement → earthquake and tsunami → uneven impacts → emergency action and reconstruction.',
      'В чек-листе указана Чили без года события. Здесь разобрано широко изучаемое землетрясение Мауле 27 февраля 2010 года. Выучи связанную цепочку: движение плит → землетрясение и цунами → неодинаковые последствия → срочная помощь и восстановление.'
    ),
    sections: [
      s('Place, event and exposure', 'Место, событие и подверженность опасности',
        'Chile is a long Pacific coastal country on the western edge of South America. The Maule earthquake struck offshore central Chile on 27 February 2010, with moment magnitude Mw 8.8. Cities, smaller settlements, ports and rural communities were exposed to different combinations of shaking and coastal flooding. Location matters: an earthquake affects a broad region, whereas tsunami exposure is concentrated in low coastal ground. A national average therefore hides major differences between a well-built urban block, an older rural house and a settlement beside the sea.',
        'Чили вытянута вдоль Тихого океана на западной окраине Южной Америки. Землетрясение Мауле произошло 27 февраля 2010 года у побережья центральной части страны; его моментная магнитуда составила Mw 8,8. Города, небольшие поселения, порты и сельские районы испытывали разные сочетания сотрясения и затопления. Положение имеет значение: землетрясение затрагивает обширную территорию, а цунами прежде всего угрожает низким участкам побережья. Средние данные по стране скрывают различия между современным городским зданием, старым сельским домом и поселением у моря.'),
      s('Why the earthquake occurred', 'Почему произошло землетрясение',
        'At this destructive subduction boundary, the oceanic Nazca Plate moves beneath the South American Plate. Friction prevents the plate boundary from slipping smoothly, although the plates continue moving. The surrounding rocks deform and store elastic strain energy. When the locked fault can no longer resist the stress, a large patch slips suddenly; released energy travels as seismic waves. This was a megathrust earthquake. The key cause is sudden fault movement, not an explosion of magma. An offshore epicentre alone does not guarantee a tsunami: substantial water displacement is required.',
        'На этой границе субдукции океаническая плита Наска погружается под Южно-Американскую плиту. Трение мешает границе скользить равномерно, хотя движение плит продолжается. Окружающие породы деформируются и накапливают энергию упругой деформации. Когда сцепленный участок разлома больше не выдерживает напряжение, происходит резкое смещение, а высвободившаяся энергия распространяется сейсмическими волнами. Это землетрясение на крупном межплитном надвиге. Его непосредственная причина — движение разлома, а не взрыв магмы. Эпицентр под океаном ещё не гарантирует цунами: необходимо значительное смещение воды.'),
      s('Primary effects: people and infrastructure', 'Первичные последствия: люди и инфраструктура',
        'Ground shaking directly damaged buildings and infrastructure, producing injuries, deaths and homelessness. These are primary effects when caused by shaking itself. The Chilean housing ministry reports 525 deaths for the combined earthquake–tsunami disaster; do not describe all of them as earthquake-collapse deaths. A government reconstruction summary estimated about 370,000 damaged homes. “Damaged” is not the same as “destroyed”. Broken transport and service networks also create a second problem: even an intact household can lose access to water, healthcare or work when the surrounding system stops functioning.',
        'Колебания грунта непосредственно повреждали здания и инфраструктуру, вызывая травмы, гибель людей и потерю жилья. Это первичные последствия, если их причиной было само сотрясение. Министерство жилищного строительства Чили указывает 525 погибших в общей катастрофе — землетрясении и цунами; нельзя считать их всех жертвами обрушения зданий. Государственный план восстановления оценивал число повреждённых домов примерно в 370 тысяч. «Повреждённые» не означает «полностью разрушенные». Разрыв транспортных и коммунальных связей создаёт дополнительную проблему: даже уцелевшая семья может потерять доступ к воде, медицине и работе.'),
      s('Secondary effects: tsunami and cascading losses', 'Вторичные последствия: цунами и цепочка потерь',
        'Seafloor movement displaced seawater and generated a tsunami, a secondary hazard triggered by the earthquake. Coastal inundation damaged settlements and altered coastal landscapes through erosion and sediment deposition. Separate the categories: direct earthquake damage is primary; tsunami flooding is secondary relative to the earthquake, even though the wave directly destroys a house. Economic losses then spread through interrupted production, transport and trade. The widely reported total loss estimate is about US$30 billion. It covers broader disaster losses, so it should not be labelled simply the cost of rebuilding houses.',
        'Смещение морского дна вытеснило воду и вызвало цунами — вторичную опасность, запущенную землетрясением. Затопление повреждало прибрежные поселения; размыв и отложение наносов меняли береговой ландшафт. Различай категории: непосредственный ущерб от сотрясения первичен, а затопление цунами вторично относительно землетрясения, хотя сама волна непосредственно разрушает дом. Экономические потери продолжают распространяться через остановку производства, транспорта и торговли. Часто приводимая общая оценка составляет около 30 млрд долларов США. Это совокупные потери катастрофы, а не только расходы на восстановление жилья.'),
      s('Immediate response: capacity and weaknesses', 'Срочная помощь: возможности и слабые места',
        'Emergency work included search and rescue, medical care and help with shelter and essential supplies. Local responders and communities sometimes acted effectively before receiving central instructions. However, damaged communications obstructed coordination and tsunami warnings. This makes Chile a useful evaluation case: relatively strong institutions can reduce losses while still suffering serious operational failures. Emergency response must link information to action; a warning has little value if it cannot reach people or if they do not understand where to go. Redundant communications and rehearsed evacuation routes address this weakness.',
        'Срочная помощь включала поиск и спасение, медицинскую помощь, предоставление временного жилья и необходимых вещей. Местные службы и жители иногда успешно действовали ещё до указаний центральных властей. Однако повреждение связи мешало координации и предупреждению о цунами. Чили полезна для оценочного ответа: сравнительно развитые службы снижают потери, но могут допускать серьёзные организационные сбои. Информация должна переходить в действие: предупреждение бесполезно, если оно не дошло до людей или они не знают, куда идти. Поэтому нужны резервные каналы связи и отработанные маршруты эвакуации.'),
      s('Long-term recovery and safer development', 'Долгосрочное восстановление и более безопасное развитие',
        'Recovery involved housing repair and replacement, restoration of infrastructure, and planning at neighbourhood, city and territorial scales. The housing programme was designed for 2010–2014; a World Bank-hosted case review reports completion of over 94% of its housing units during that period. This is a programme indicator, not proof that every person had fully recovered. Reconstruction also faces land ownership, affordability and access problems. A stronger house reduces structural vulnerability, but families also need livelihoods, functioning services and a safe location. Rebuilding previous exposure can reproduce future risk.',
        'Восстановление включало ремонт и замену жилья, восстановление инфраструктуры и планирование на уровне районов, городов и территорий. Жилищная программа была рассчитана на 2010–2014 годы; размещённый Всемирным банком разбор сообщает о выполнении более 94% предусмотренного объёма жилья за этот период. Это показатель программы, а не доказательство полного восстановления жизни каждого человека. Возникают вопросы собственности на землю, доступности жилья и услуг. Прочный дом снижает уязвимость конструкции, но семье также нужны доход, работающие службы и безопасное местоположение. Возвращение прежней подверженности опасности воспроизводит риск.'),
      s('Evaluation: what explains the outcome?', 'Оценка: чем объясняется результат?',
        'Chile illustrates the value of enforced seismic building standards: many engineered buildings resisted extremely strong shaking. Yet older or poorly constructed homes, coastal exposure and warning failures remained important. Compared with Nepal, Chile had greater financial and engineering capacity, but wealth alone is not a full explanation. Compare building quality, settlement location, terrain, emergency access and secondary hazards as well as magnitude. The strongest conclusion is conditional: investment reduces vulnerability when standards are actually followed and response systems work. It does not remove tectonic activity or make every community equally safe.',
        'Чили показывает пользу соблюдения сейсмических строительных норм: многие инженерно спроектированные здания выдержали очень сильное сотрясение. Однако старое или некачественное жильё, расположение у моря и сбои предупреждения сохраняли опасность. По сравнению с Непалом Чили располагала большими финансовыми и инженерными возможностями, но только богатством результат не объяснить. Сравнивай качество зданий, положение поселений, рельеф, доступ спасателей, вторичные опасности и магнитуду. Обоснованный вывод имеет условие: вложения снижают уязвимость, когда нормы действительно соблюдаются и службы работают. Они не прекращают тектонические процессы и не делают все сообщества одинаково защищёнными.')
    ],
    keyFacts: [
      b('27 February 2010; Mw 8.8; Nazca Plate subducting beneath South America (USGS).', '27 февраля 2010 года; Mw 8,8; плита Наска погружается под Южно-Американскую (USGS).'),
      b('Use “about 500 deaths” for a robust rounded figure; MINVU reports 525. Earlier reports differ and count missing people separately.', 'Устойчивая округлённая оценка — около 500 погибших; MINVU указывает 525. Ранние отчёты отличаются и отдельно учитывают пропавших.'),
      b('About 370,000 damaged homes in the government reconstruction summary; about US$30 billion total losses. Keep category and source with each figure.', 'Около 370 тысяч повреждённых домов по государственному плану восстановления; около 30 млрд долларов общих потерь. Помни, что именно измеряет каждая цифра.'),
      b('A tsunami is a secondary hazard of this earthquake. Not every Chilean fatality or damaged building was caused by shaking.', 'Цунами — вторичная опасность этого землетрясения. Не вся гибель людей и не все повреждения зданий были вызваны сотрясением.')
    ],
    example: {
      question: b('Explain why a very large earthquake did not produce the same impacts everywhere in Chile.', 'Объясни, почему очень сильное землетрясение вызвало разные последствия в разных частях Чили.'),
      steps: [
        b('Identify exposure: low coastal settlements also faced tsunami flooding, whereas inland settlements did not face that particular hazard.', 'Укажи подверженность опасности: низкие прибрежные поселения испытывали ещё и затопление цунами; во внутренних районах этой конкретной опасности не было.'),
        b('Explain vulnerability: an engineered building with a continuous load path is less likely to collapse than weak, poorly connected masonry under comparable shaking.', 'Объясни уязвимость: инженерно рассчитанное здание с надёжной связью элементов менее склонно к обрушению, чем слабая кладка при сопоставимом сотрясении.'),
        b('Add response capacity: functioning local services and communication can speed assistance; isolated or disconnected communities face longer delays.', 'Добавь возможности реагирования: работающие местные службы и связь ускоряют помощь, а изолированные сообщества получают её позднее.'),
        b('Judge: the hazard was regional, but exposure, construction and response varied locally; magnitude alone cannot explain the pattern.', 'Сделай вывод: опасное событие охватило регион, но положение, качество зданий и помощь различались; одной магнитуды недостаточно для объяснения.')
      ]
    },
    pitfalls: [
      b('Do not reverse the plates: Nazca goes beneath South America.', 'Не меняй плиты местами: Наска погружается под Южно-Американскую.'),
      b('Do not call Mw 8.8 an intensity value or an accurate use of the Richter scale.', 'Не называй Mw 8,8 интенсивностью и не приписывай это значение шкале Рихтера.'),
      b('Do not merge “felt shaking”, “affected”, “displaced” and “homeless”: they count different populations.', 'Не смешивай «ощутили толчки», «пострадали», «переселились» и «потеряли жильё»: это разные группы.'),
      b('Do not conclude that strict building codes solved the tsunami-warning problem.', 'Не делай вывод, что строгие строительные нормы решили проблему предупреждения о цунами.')
    ],
    questions: [
      { id: 'chile-causes', topic: 'chile', prompt: b('Explain the tectonic cause of the 2010 Chile earthquake.', 'Объясни тектоническую причину землетрясения в Чили 2010 года.'), hint: b('Name both plates, then explain locking, strain and rupture.', 'Назови обе плиты, затем объясни сцепление, деформацию и срыв.'), marking: [b('Nazca oceanic plate subducts beneath South America.', 'Океаническая Наска погружается под Южно-Американскую плиту.'), b('Friction locks part of the boundary while plate motion continues.', 'Трение сцепляет часть границы, хотя движение плит продолжается.'), b('Elastic strain accumulates until sudden thrust slip releases seismic waves.', 'Упругая деформация накапливается, затем резкое смещение высвобождает сейсмические волны.')] },
      { id: 'chile-effects', topic: 'chile', prompt: b('Explain one primary and one secondary effect, linking each to people or the economy.', 'Объясни одно первичное и одно вторичное последствие, связав каждое с людьми или экономикой.'), hint: b('Classify by the causal chain, not by how many hours passed.', 'Классифицируй по причинной цепочке, а не по числу прошедших часов.'), marking: [b('Primary: shaking damaged buildings or infrastructure.', 'Первичное: сотрясение повредило здания или инфраструктуру.'), b('Explain resulting injury, homelessness or loss of essential access.', 'Объяснены травмы, потеря жилья или доступа к жизненно важным услугам.'), b('Secondary: earthquake-induced seafloor displacement generated tsunami flooding.', 'Вторичное: смещение дна при землетрясении вызвало затопление цунами.'), b('Connect the flooding to coastal losses, displacement or disrupted livelihoods.', 'Затопление связано с прибрежным ущербом, переселением или потерей дохода.')] },
      { id: 'chile-evaluate', topic: 'chile', prompt: b('Evaluate the statement: “Chile shows that wealth prevents earthquake disasters.”', 'Оцени утверждение: «Чили показывает, что богатство предотвращает катастрофы при землетрясениях».'), hint: b('Support, limitation, then a qualified judgement.', 'Довод в поддержку, ограничение, затем взвешенный вывод.'), marking: [b('Resources can support engineering, enforcement and emergency services.', 'Ресурсы поддерживают инженерные решения, соблюдение норм и спасательные службы.'), b('Use Chile’s building performance as evidence of reduced vulnerability.', 'Работа конструкций в Чили приведена как пример снижения уязвимости.'), b('Discuss remaining tsunami exposure, communication failures or unequal housing quality.', 'Обсуждены угроза цунами, сбои связи или неодинаковое качество жилья.'), b('Conclude that wealth can reduce disaster risk but cannot eliminate the physical hazard.', 'Вывод: богатство может снизить риск катастрофы, но не устранить физическую опасность.')] }
    ],
    sourceIds: ['chile-usgs', 'chile-impact', 'chile-housing', 'chile-plan', 'chile-tsunami', 'chile-recovery', 'chile-governance']
  },
  {
    id: 'nepal', title: b('Nepal: the Gorkha earthquake, 2015', 'Непал: землетрясение Горкха, 2015'), checklist: [7], visual: 'collision',
    intro: b('The checklist names Nepal without a year. This lesson uses the 25 April 2015 Gorkha earthquake and distinguishes its main shock from the damaging May aftershock and the wider earthquake sequence.', 'В чек-листе Непал указан без года. Здесь рассматривается землетрясение Горкха 25 апреля 2015 года; основной толчок отделён от разрушительного майского афтершока и всей серии землетрясений.'),
    sections: [
      s('Setting and event', 'Положение и событие',
        'Nepal is a mountainous, landlocked country in the Himalayas between India and China. On 25 April 2015 a shallow Mw 7.8 earthquake struck near Gorkha, northwest of Kathmandu. A Mw 7.3 aftershock followed on 12 May. The main rupture propagated towards the Kathmandu region. Both densely occupied settlements and remote mountain communities were exposed, but in different ways. Urban concentration put many buildings and services at risk; steep terrain made secondary landslides and difficult access especially important outside the capital. Always specify whether a statistic describes April alone or the wider sequence.',
        'Непал — горная страна без выхода к морю, расположенная в Гималаях между Индией и Китаем. 25 апреля 2015 года близ Горкхи, к северо-западу от Катманду, произошло неглубокое землетрясение Mw 7,8. 12 мая последовал афтершок Mw 7,3. Разрыв основного толчка распространялся в сторону района Катманду. Опасность угрожала и плотно заселённым районам, и удалённым горным общинам, но по-разному. В городах было много зданий и служб, а в горах особенно важными стали оползни и труднодоступность. Всегда уточняй, относится ли статистика только к апрелю или ко всей серии.'),
      s('Collision, thrusting and stored energy', 'Столкновение плит, надвиг и накопление энергии',
        'The Indian and Eurasian continental plates converge. India underthrusts the Himalayan region, compressing and thickening the crust and helping uplift the mountains. Parts of the Main Himalayan Thrust can remain locked while motion continues elsewhere. Stress and elastic strain build until a fault segment slips suddenly, releasing earthquake waves. This is the collision setting required by the checklist. It is not an oceanic plate sinking beneath Nepal to generate a volcanic arc: continental collision produces major earthquakes and mountain building without the typical subduction-zone chain of active volcanoes.',
        'Индийская и Евразийская континентальные плиты сближаются. Индийская плита поддвигается под Гималаи, сжимая и утолщая кору и способствуя поднятию гор. Участки Главного Гималайского надвига могут оставаться сцепленными, пока движение продолжается в других местах. Напряжение и упругая деформация накапливаются до резкого смещения разлома, высвобождающего сейсмические волны. Это требуемый чек-листом пример столкновения континентов. Здесь океаническая плита не погружается под Непал с образованием вулканической дуги: столкновение континентов вызывает крупные землетрясения и горообразование без типичной цепи действующих вулканов.'),
      s('Primary social and economic impacts', 'Первичные социальные и экономические последствия',
        'Shaking collapsed or damaged homes, schools, health facilities and historic buildings. Weak masonry and inadequate connections between walls, floors and roofs increased the chance of collapse. Direct consequences included deaths, injuries and loss of shelter; damage to workplaces and infrastructure also destroyed economic assets. The government’s 2015 needs assessment recorded roughly half a million homes destroyed and over 250,000 damaged. A useful rounded human-impact summary is about 9,000 deaths and more than 22,000 injuries across the 2015 disaster; totals vary with reporting date and which events are included.',
        'Толчки разрушили или повредили дома, школы, медицинские учреждения и исторические здания. Слабая кладка и ненадёжные соединения стен, перекрытий и крыш повышали вероятность обрушения. Непосредственными последствиями стали гибель людей, травмы и потеря жилья; повреждения предприятий и инфраструктуры уничтожали экономические активы. Государственная оценка потребностей 2015 года указывала около полумиллиона разрушенных и более 250 тысяч повреждённых домов. Для запоминания подходит округление: около 9 тысяч погибших и более 22 тысяч пострадавших с травмами в катастрофе 2015 года. Итоги зависят от даты подсчёта и включённых событий.'),
      s('Secondary hazards and cascading impacts', 'Вторичные опасности и цепочки последствий',
        'Earthquake shaking destabilised steep slopes, triggering landslides, rockfalls and avalanches. Debris could bury settlements, block roads or obstruct rivers, creating further flood risks. These are secondary hazards because the initial shaking set them in motion. Their human consequences extend beyond the impact zone: a blocked route delays relief, interrupts trade and restricts healthcare access. Displacement and damaged water systems increase sanitation problems, while interrupted education and tourism affect longer-term recovery. Do not claim that a particular disease epidemic occurred simply because conditions made it possible; distinguish documented effects from potential risks.',
        'Сотрясение нарушило устойчивость крутых склонов, вызвав оползни, камнепады и лавины. Обломки могли засыпать поселения, перекрывать дороги и перегораживать реки, создавая риск дальнейшего затопления. Это вторичные опасности: их запустили первоначальные толчки. Последствия выходят за пределы зоны обвала: перекрытый путь задерживает помощь, нарушает торговлю и доступ к врачам. Переселение и повреждение водоснабжения осложняют санитарные условия; перерывы в учёбе и туризме влияют на восстановление. Нельзя утверждать, что произошла конкретная эпидемия, только потому, что возникли благоприятные для неё условия: отделяй подтверждённые последствия от рисков.'),
      s('Emergency response and access constraints', 'Срочная помощь и трудности доступа',
        'Local people, Nepalese responders and international organisations carried out rescue, medical assistance and distribution of shelter materials, food and safe water. Red Cross operations also included sanitation, health support and cash assistance. These measures address different needs: rescuing trapped people saves lives immediately, whereas shelter and clean water reduce exposure after the shock. Mountain terrain, blocked routes, damaged services and continuing aftershocks complicated delivery. Aid arriving in the country is not the same as aid reaching a remote household. Effective response requires local knowledge, coordination and transport capacity as well as donated supplies.',
        'Местные жители, непальские службы и международные организации проводили спасательные работы, оказывали медицинскую помощь, доставляли материалы для укрытий, еду и безопасную воду. Программы Красного Креста также включали санитарию, поддержку здоровья и денежную помощь. Эти действия решают разные задачи: освобождение из-под завалов спасает жизнь немедленно, а жильё и чистая вода уменьшают последующую уязвимость. Горы, перекрытые пути, повреждённые службы и афтершоки осложняли доставку. Прибытие груза в страну ещё не означает помощь удалённой семье. Необходимы местные знания, координация и транспорт, а не только пожертвования.'),
      s('Reconstruction: build back safer', 'Восстановление: строить безопаснее',
        'Nepal’s recovery required both finance and construction skills. The government-led assessment put damage and economic losses at about US$7 billion and recovery needs at about US$6.7 billion; these are different measures, not contradictory totals. Housing reconstruction supported owner-driven rebuilding, trained engineers and masons, and encouraged earthquake-resistant methods. A 2020 World Bank project report described support aimed at over 330,000 poor rural homeowners. That figure refers to the project’s scope, not all affected households. Safer recovery also requires land access, inspections, affordable materials and attention to people who cannot rebuild without additional support.',
        'Для восстановления Непала требовались и деньги, и строительные навыки. Государственная оценка определила ущерб и экономические потери примерно в 7 млрд долларов, а потребности восстановления — примерно в 6,7 млрд. Это разные показатели, а не противоречащие итоги. Программы помогали владельцам восстанавливать жильё, обучали инженеров и каменщиков, внедряли сейсмостойкое строительство. В отчёте Всемирного банка за 2020 год описана поддержка, рассчитанная более чем на 330 тысяч малообеспеченных сельских домовладельцев. Это охват проекта, а не все пострадавшие семьи. Также нужны земля, проверки, доступные материалы и помощь тем, кто не может восстановиться самостоятельно.'),
      s('Compare Nepal with Chile fairly', 'Как корректно сравнивать Непал и Чили',
        'Nepal’s main shock had a lower magnitude than Chile’s, yet the Nepal disaster caused far more deaths. This shows that magnitude is not a death-toll formula. More vulnerable buildings, limited resources and difficult mountain access help explain Nepal’s outcome; stronger engineering and response capacity reduced vulnerability in Chile. However, this is not a controlled experiment: distance from rupture, local ground conditions, exposure and secondary hazards also differed. Compare absolute money losses with losses relative to available resources. A smaller financial loss can still be much harder for a poorer society to recover from.',
        'Магнитуда основного непальского толчка была ниже, чем чилийского, но погибших оказалось значительно больше. Значит, магнитуда не является формулой числа жертв. Более уязвимые здания, ограниченные ресурсы и труднодоступность гор помогают объяснить результат Непала; инженерные решения и службы Чили снижали уязвимость. Однако это не контролируемый эксперимент: различались расстояние до разрыва, местные грунты, подверженность людей и вторичные опасности. Сравнивай не только абсолютные денежные потери, но и их отношение к доступным ресурсам. Меньший денежный ущерб может оказаться намного тяжелее для восстановления более бедного общества.')
    ],
    keyFacts: [
      b('25 April 2015: Mw 7.8 main shock; 12 May: Mw 7.3 aftershock. Use moment magnitude, not “Richter”, for these values.', '25 апреля 2015 года: основной толчок Mw 7,8; 12 мая: афтершок Mw 7,3. Эти значения — моментная магнитуда, а не «шкала Рихтера».'),
      b('Indian–Eurasian collision; rupture on the Main Himalayan Thrust. A shallow event, but exact published depth estimates differ.', 'Столкновение Индийской и Евразийской плит; разрыв на Главном Гималайском надвиге. Очаг неглубокий, но точные оценки глубины различаются.'),
      b('About 9,000 deaths and over 22,000 injuries are useful rounded disaster totals; do not combine exact totals from different dated reports.', 'Около 9 тысяч погибших и более 22 тысяч травмированных — удобные округлённые итоги катастрофы; не смешивай точные данные из отчётов разных дат.'),
      b('About US$7 billion damage and losses; about US$6.7 billion recovery needs (2015 PDNA). “Losses” and “recovery needs” are not identical.', 'Около 7 млрд долларов ущерба и потерь; около 6,7 млрд потребностей восстановления по оценке PDNA 2015 года. «Потери» и «потребности» — разные показатели.')
    ],
    example: {
      question: b('Explain why mountainous terrain increased the disaster’s impacts in Nepal.', 'Объясни, почему горный рельеф усилил последствия катастрофы в Непале.'),
      steps: [
        b('Start with a physical mechanism: shaking destabilises steep slopes, so gravity can move rock, soil, snow and ice downhill.', 'Начни с механизма: толчки нарушают устойчивость крутых склонов, и сила тяжести перемещает камни, грунт, снег и лёд вниз.'),
        b('Identify the direct consequence of the secondary hazard: debris can bury buildings or block the few available roads.', 'Назови непосредственный результат вторичной опасности: обломки засыпают здания или перекрывают немногочисленные дороги.'),
        b('Extend the causal chain: blocked roads delay medical help and delivery of shelter, water and food.', 'Продолжи причинную цепочку: перекрытые дороги задерживают врачей, доставку укрытий, воды и пищи.'),
        b('Evaluate: aircraft can help reach isolated places, but weather, capacity and landing sites limit this solution.', 'Оцени решение: авиация помогает добраться до изолированных районов, но ограничена погодой, вместимостью и местами посадки.')
      ]
    },
    pitfalls: [
      b('Do not describe Nepal as an oceanic subduction volcanic-arc example.', 'Не представляй Непал примером океанической субдукции с вулканической дугой.'),
      b('Do not treat the May aftershock as the date or magnitude of the April main shock.', 'Не подменяй дату и магнитуду апрельского основного толчка данными майского афтершока.'),
      b('Do not attribute every death in a sequence-wide total to one moment of building collapse.', 'Не приписывай всех погибших за серию землетрясений одному моменту обрушения зданий.'),
      b('Avoid “poor countries have no building rules”; distinguish standards, affordability, skills and enforcement.', 'Не пиши «в бедных странах нет строительных норм»: различай нормы, стоимость, навыки и контроль исполнения.')
    ],
    questions: [
      { id: 'nepal-causes', topic: 'nepal', prompt: b('Explain how continental collision caused the 2015 Nepal earthquake.', 'Объясни, как столкновение континентов вызвало землетрясение в Непале 2015 года.'), hint: b('Link plate movement to strain and sudden fault slip.', 'Свяжи движение плит с деформацией и резким смещением разлома.'), marking: [b('Indian and Eurasian plates converge; India underthrusts the Himalayas.', 'Индийская и Евразийская плиты сближаются; Индийская поддвигается под Гималаи.'), b('A locked thrust fault accumulates strain.', 'На сцепленном надвиге накапливается деформация.'), b('Sudden slip releases energy as seismic waves.', 'Резкий сдвиг высвобождает энергию сейсмическими волнами.'), b('Distinguish mountain-building collision from a typical oceanic volcanic arc.', 'Столкновение с горообразованием отличается от типичной океанической вулканической дуги.')] },
      { id: 'nepal-secondary', topic: 'nepal', prompt: b('Explain two ways secondary hazards made relief harder in Nepal.', 'Объясни два способа, которыми вторичные опасности осложняли помощь в Непале.'), hint: b('Think about slopes, roads, rivers and access.', 'Подумай о склонах, дорогах, реках и доступе.'), marking: [b('Shaking triggered landslides or avalanches.', 'Толчки вызвали оползни или лавины.'), b('Blocked roads isolated communities and delayed supplies or treatment.', 'Перекрытые дороги изолировали поселения и задерживали помощь.'), b('Unstable slopes or river blockages created further dangers for residents and rescuers.', 'Неустойчивые склоны или перекрытые реки создавали дополнительные угрозы жителям и спасателям.'), b('Explain the mechanism, rather than merely listing “landslides” and “floods”.', 'Дан механизм, а не только список «оползни» и «наводнения».')] },
      { id: 'nepal-chile', topic: 'nepal', prompt: b('Why is earthquake magnitude insufficient to explain the different death tolls in Nepal and Chile?', 'Почему магнитуды недостаточно для объяснения разницы в числе погибших в Непале и Чили?'), hint: b('Use vulnerability, exposure and capacity, then acknowledge other physical factors.', 'Используй уязвимость, подверженность опасности и возможности помощи; учти другие физические факторы.'), marking: [b('Nepal had a smaller main-shock magnitude but a much larger death toll.', 'В Непале магнитуда основного толчка была меньше, но погибших значительно больше.'), b('Explain differences in building vulnerability and implementation of seismic design.', 'Объяснены различия уязвимости зданий и применения сейсмостойких решений.'), b('Explain the effect of resources and mountain access on assistance.', 'Объяснено влияние ресурсов и труднодоступности гор на помощь.'), b('Acknowledge that ground conditions, location and secondary hazards also differed.', 'Учтены различия грунтов, положения и вторичных опасностей.'), b('Conclude that disaster impacts result from interacting physical and human factors.', 'Вывод связывает последствия с взаимодействием природных и общественных факторов.')] }
    ],
    sourceIds: ['nepal-usgs', 'nepal-tectonics', 'nepal-pdna', 'nepal-landslides', 'nepal-response', 'nepal-recovery', 'nepal-losses']
  },
  {
    id: 'eyjafjallajokull', title: b('Eyjafjallajökull: Iceland, 2010', 'Эйяфьядлайёкюдль: Исландия, 2010'), checklist: [8], visual: 'volcano',
    intro: b('The checklist does not give a year. This lesson uses the 2010 eruption, especially the explosive summit phase beginning on 14 April. Its distinctive lesson is how a local volcanic hazard disrupted international transport.', 'Год в чек-листе не указан. Здесь рассматривается извержение 2010 года, особенно взрывная вершинная фаза с 14 апреля. Главная особенность примера — превращение локальной вулканической опасности в международное транспортное нарушение.'),
    sections: [
      s('Iceland’s setting and this particular volcano', 'Положение Исландии и особенности вулкана',
        'Iceland straddles the divergent boundary between the North American and Eurasian plates and also has a hotspot-related magma supply. Separation and mantle upwelling favour melting and volcanism. Eyjafjallajökull is an ice-covered central volcano in southern Iceland with a composite volcanic edifice. Do not assume that every volcano in a constructive setting is a simple shield with harmless lava. Magma composition, gas content, the vent system and contact with ice or water influence eruption style. A regional plate setting explains the magma supply; local conditions explain much of the particular hazard.',
        'Исландия пересекает расходящуюся границу Северо-Американской и Евразийской плит; дополнительный источник магмы связан с горячей точкой. Расхождение и подъём мантийного вещества способствуют плавлению и вулканизму. Эйяфьядлайёкюдль — покрытый льдом центральный вулкан на юге острова со сложным слоистым сооружением. Нельзя считать любой вулкан на границе расхождения простым щитом с безобидной лавой. Стиль извержения зависит от состава магмы, газов, системы каналов и контакта со льдом или водой. Тектоническое положение объясняет поступление магмы, а местные условия — многие конкретные опасности.'),
      s('The eruption sequence and explosive mechanism', 'Последовательность извержения и взрывной механизм',
        'An initial flank fissure eruption began on 20 March 2010. On 14 April activity moved to the ice-covered summit area. Hot magma and meltwater interacted, rapidly producing steam and fragmenting magma into fine ash; escaping volcanic gases also contributed to explosive activity. This explains why a divergent-boundary volcano generated an ash crisis. Wind then carried ash away from Iceland towards busy European air routes. The main explosive phase lasted into late May. Different accounts use 22 or 23 May as the endpoint, so “April–May 2010” avoids false precision.',
        'Первое извержение из трещины на склоне началось 20 марта 2010 года. 14 апреля активность переместилась в покрытую льдом вершинную область. Контакт горячей магмы с талой водой быстро образовывал пар и дробил магму на мелкий пепел; выход вулканических газов также поддерживал взрывную активность. Поэтому вулкан на границе расхождения вызвал пепловый кризис. Ветер переносил пепел из Исландии к загруженным европейским воздушным трассам. Основная взрывная фаза продолжалась до конца мая. В источниках встречаются 22 и 23 мая; формулировка «апрель–май 2010 года» избегает ложной точности.'),
      s('Local primary effects: ash and exposure', 'Местные первичные последствия: пепел и воздействие',
        'Ashfall was a direct, primary effect of the eruption. Fine abrasive particles reduced visibility, contaminated surfaces and affected homes and farmland. Icelandic monitoring found fluorine in the ash, creating a hazard when livestock consumed contaminated feed or water. Local health research recorded eye and upper-airway irritation and worsening symptoms among some people with asthma. A small early study found no eruption-attributable serious hospital cases in its cohort; this does not mean that ash was harmless or that every exposed person had the same outcome. Exposure level and existing health conditions matter.',
        'Выпадение пепла — непосредственное первичное последствие извержения. Мелкие абразивные частицы снижали видимость, загрязняли поверхности, затрагивали дома и сельскохозяйственные земли. Исландский мониторинг обнаружил в пепле фтор: загрязнённые корм и вода создавали угрозу скоту. Исследование местных жителей зафиксировало раздражение глаз и верхних дыхательных путей, а у некоторых людей с астмой — усиление симптомов. В небольшой ранней группе не выявили связанных с извержением тяжёлых случаев, потребовавших госпитализации. Это не означает безвредности пепла или одинакового исхода для всех: важны доза воздействия и исходное здоровье.'),
      s('Secondary local hazard: glacier-outburst flooding', 'Местная вторичная опасность: прорывные ледниковые паводки',
        'Heat melted glacier ice, and rapidly released meltwater produced jökulhlaups: sudden glacier-outburst floods. Relative to the eruption, these are secondary hazards. Water and debris moved down drainage routes, damaging roads and protective embankments. This creates a chain from physical process to social and economic impact: flooding → damaged access → disrupted movement and farm activity. Hazard maps must therefore include valleys and flood routes, not just a circle around the crater. Evacuating people from the vent alone would leave communities in downstream flood paths exposed.',
        'Тепло растапливало ледник; быстрый выход талой воды вызывал йёкюльхлёйпы — внезапные прорывные ледниковые паводки. По отношению к извержению это вторичные опасности. Вода с обломками двигалась по руслам и долинам, повреждала дороги и защитные насыпи. Получается цепочка от природного процесса к общественным и экономическим последствиям: затопление → повреждение путей доступа → нарушение перевозок и работы хозяйств. Поэтому карта опасности должна учитывать долины и пути стока, а не только круг вокруг кратера. Эвакуация лишь возле жерла оставила бы незащищёнными людей ниже по течению.'),
      s('International impacts: aviation and connected economies', 'Международные последствия: авиация и связанные экономики',
        'Volcanic ash can abrade aircraft surfaces and damage engines, so national authorities restricted airspace as the cloud spread. These closures were a protective response; cancelled journeys and interrupted business were resulting secondary economic and social impacts. EUROCONTROL estimated 104,000 cancelled flights and around 10 million disrupted passenger journeys during the main April crisis. Passenger journeys are not necessarily unique people. Airlines lost revenue and passengers faced delays, accommodation costs and missed commitments. This case shows that geographic distance from a volcano does not prevent impact when transport networks connect distant places.',
        'Вулканический пепел повреждает поверхности самолётов и двигатели, поэтому национальные власти ограничивали воздушное пространство по мере распространения облака. Закрытие было защитной мерой; отменённые поездки и нарушение бизнеса — последующими вторичными социальными и экономическими последствиями. EUROCONTROL оценил главный апрельский кризис в 104 тысячи отменённых рейсов и примерно 10 млн нарушенных пассажирских поездок. Число поездок не равно числу уникальных людей. Авиакомпании теряли выручку, пассажиры сталкивались с задержками, расходами на жильё и сорванными планами. Транспортные связи позволяют воздействию вулкана распространяться далеко от места извержения.'),
      s('Immediate management: monitoring and protective action', 'Срочные меры: наблюдение и защита',
        'Icelandic authorities monitored volcanic activity and river conditions, issued updates, restricted access and evacuated people from flood-risk areas. A government update on 14 April reported around 700 evacuees; later school summaries often use around 800, reflecting different reporting moments. Monitoring is useful only when translated into action. Locally, forecasts support evacuation and ash-exposure reduction; internationally, the London Volcanic Ash Advisory Centre supplied ash information and national aviation authorities made airspace decisions. These roles should be distinguished: scientists estimate hazards, while responsible authorities decide and organise protective measures.',
        'Исландские службы наблюдали за вулканом и реками, выпускали сообщения, ограничивали доступ и эвакуировали жителей зон возможного затопления. Правительственное сообщение 14 апреля указывало около 700 эвакуированных; в более поздних учебных обзорах часто встречается около 800 — это разные моменты учёта. Мониторинг полезен, когда приводит к действию. На месте прогнозы помогают эвакуации и снижению контакта с пеплом; на международном уровне Лондонский центр предупреждения о вулканическом пепле предоставлял данные, а национальные авиационные власти принимали решения. Учёные оценивают опасность; уполномоченные органы организуют защиту.'),
      s('Longer-term management and evaluation', 'Долгосрочные меры и оценка',
        'After the crisis, European aviation improved coordination, ash-dispersion information and procedures for managing contaminated airspace. The European Aviation Crisis Coordination Cell was formally established in 2011. This is a long-term management response, distinct from the immediate cancellation of a flight. Locally, recovery includes clearing ash, restoring access and continuing observation where ash can be remobilised. No monitoring system removes uncertainty: wind changes, ash concentration varies and eruption duration is hard to forecast. Effective management balances life safety with disruption, updates decisions as evidence improves, and communicates what remains uncertain.',
        'После кризиса европейская авиация улучшала координацию, информацию о переносе пепла и процедуры работы с загрязнённым воздушным пространством. В 2011 году был официально создан Европейский центр координации авиационных кризисов. Это долгосрочная мера управления, отличная от немедленной отмены рейса. Местное восстановление включает уборку пепла, восстановление доступа и наблюдение там, где пепел снова поднимается ветром. Ни одна система не устраняет неопределённость: ветер меняется, концентрация пепла неодинакова, продолжительность извержения трудно предсказать. Необходимо сопоставлять безопасность и нарушения, обновлять решения по новым данным и объяснять оставшиеся неизвестные.')
    ],
    keyFacts: [
      b('2010: flank fissure phase began 20 March; explosive summit phase began 14 April and continued into late May (IMO).', '2010 год: трещинная фаза началась 20 марта; взрывная вершинная — 14 апреля и продолжалась до конца мая (IMO).'),
      b('Divergent North American–Eurasian setting plus a hotspot; ice–magma interaction helped generate fine ash.', 'Расхождение Северо-Американской и Евразийской плит плюс горячая точка; контакт льда, воды и магмы способствовал образованию мелкого пепла.'),
      b('About 104,000 cancelled flights and 10 million disrupted passenger journeys in the April crisis (EUROCONTROL); use that reporting window.', 'Около 104 тысяч отменённых рейсов и 10 млн нарушенных пассажирских поездок в апрельский кризис (EUROCONTROL); сохраняй этот период учёта.'),
      b('IATA’s contemporaneous estimate: US$1.7 billion in lost airline revenue, not the total economic cost of the eruption.', 'Тогдашняя оценка IATA: 1,7 млрд долларов потерянной выручки авиакомпаний, а не общий экономический ущерб от извержения.'),
      b('A jökulhlaup is a glacier-outburst flood; it is not the Icelandic name for an ash cloud or a tsunami.', 'Йёкюльхлёйп — прорывной ледниковый паводок; это не исландское название пеплового облака или цунами.')
    ],
    example: {
      question: b('Explain how an Icelandic eruption caused losses in countries far from Iceland.', 'Объясни, как исландское извержение вызвало потери в далёких странах.'),
      steps: [
        b('Explain production: explosive fragmentation produced fine volcanic ash.', 'Объясни образование: взрывное дробление магмы создало мелкий вулканический пепел.'),
        b('Explain transport: atmospheric winds carried particles into international air routes.', 'Объясни перенос: атмосферные ветры перенесли частицы в зоны международных воздушных трасс.'),
        b('Explain the management decision: ash threatened aircraft safety, so authorities restricted flights.', 'Объясни решение: пепел угрожал безопасности самолётов, поэтому власти ограничили полёты.'),
        b('Explain consequences: cancelled flights reduced airline revenue and disrupted travel and business; connect this to global interdependence.', 'Объясни последствия: отмены сократили выручку авиакомпаний и нарушили поездки и бизнес; свяжи это с международной взаимозависимостью.')
      ]
    },
    pitfalls: [
      b('Do not say destructive subduction caused Iceland’s volcanism.', 'Не объясняй исландский вулканизм границей субдукции.'),
      b('Do not assume a constructive setting guarantees only gentle shield eruptions.', 'Не считай, что граница расхождения гарантирует только спокойные извержения щитовых вулканов.'),
      b('Do not call ash smoke: it contains fragments of volcanic rock, minerals and glass.', 'Не называй пепел дымом: он содержит обломки вулканических пород, минералов и стекла.'),
      b('Do not claim that airspace closures were themselves a natural hazard; they were a protective response with economic consequences.', 'Закрытие воздушного пространства — не природная опасность, а защитная мера с экономическими последствиями.'),
      b('Do not equate no reported immediate fatalities with no health, livelihood or financial harm.', 'Отсутствие зарегистрированной немедленной гибели не означает отсутствия вреда здоровью, доходам и экономике.')
    ],
    questions: [
      { id: 'iceland-explosive', topic: 'eyjafjallajokull', prompt: b('Why did this eruption produce an explosive ash hazard despite Iceland’s constructive setting?', 'Почему при конструктивной границе в Исландии это извержение создало взрывную пепловую опасность?'), hint: b('Separate the regional magma supply from the local eruption mechanism.', 'Отдели региональное поступление магмы от местного механизма извержения.'), marking: [b('Plate divergence and hotspot activity explain magma supply.', 'Расхождение плит и горячая точка объясняют поступление магмы.'), b('The summit eruption occurred beneath ice.', 'Вершинное извержение происходило подо льдом.'), b('Magma–meltwater interaction produced rapid steam expansion and fragmentation.', 'Контакт магмы с талой водой вызывал быстрое расширение пара и дробление.'), b('Fine ash could be carried far by atmospheric winds.', 'Мелкий пепел мог переноситься далеко атмосферными ветрами.')] },
      { id: 'iceland-effects', topic: 'eyjafjallajokull', prompt: b('Explain one local and one international impact of the eruption, identifying the causal chain.', 'Объясни одно местное и одно международное последствие извержения через причинные цепочки.'), hint: b('Use meltwater or ash locally, and aircraft risk internationally.', 'Для местного примера используй талую воду или пепел, для международного — риск авиации.'), marking: [b('A valid local effect such as ash exposure or glacier-outburst flooding.', 'Названо местное последствие, например воздействие пепла или ледниковый паводок.'), b('Explain the physical mechanism and effect on people, infrastructure or farming.', 'Объяснены физический механизм и влияние на людей, инфраструктуру или сельское хозяйство.'), b('Wind spread ash into air routes and created an aircraft hazard.', 'Ветер перенёс пепел на воздушные трассы и создал опасность самолётам.'), b('Restrictions and cancellations disrupted journeys and economic activity.', 'Ограничения и отмены нарушили поездки и хозяйственную деятельность.')] },
      { id: 'iceland-management', topic: 'eyjafjallajokull', prompt: b('Evaluate how monitoring helped manage the eruption and why it could not remove all impacts.', 'Оцени, как мониторинг помог управлять извержением и почему не устранил все последствия.'), hint: b('Observation → warning → action, followed by a limitation.', 'Наблюдение → предупреждение → действие, затем ограничение.'), marking: [b('Volcano, river or ash observations provided relevant hazard information.', 'Наблюдения за вулканом, реками или пеплом давали информацию об опасности.'), b('Link information to evacuation, access restrictions or aviation decisions.', 'Информация связана с эвакуацией, ограничением доступа или авиационными решениями.'), b('Recognise uncertain eruption timing, duration, winds or ash concentrations.', 'Признана неопределённость сроков, длительности, ветра или концентрации пепла.'), b('Protective action can reduce injury risk while still causing disruption and cost.', 'Защитные меры снижают риск травм, но всё равно вызывают нарушения и затраты.'), b('Give a judgement about combined monitoring, communication and practical action.', 'Сделан вывод о сочетании наблюдения, связи и практических действий.')] }
    ],
    sourceIds: ['iceland-imo', 'iceland-hotspot', 'iceland-profile', 'iceland-plates', 'iceland-eruption', 'iceland-ash', 'iceland-health', 'iceland-floods', 'iceland-evacuation', 'aviation-eurocontrol', 'aviation-iata', 'aviation-recovery', 'aviation-usgs']
  }
];
