import { b, type Bilingual, type Source } from './types';
import { caseSources } from './case-sources';

export const checklist: {id:number;text:Bilingual}[] = [
  {id:1,text:b('Name the four plate boundaries', 'Назвать четыре типа границ плит')},
  {id:2,text:b('Explain processes and characteristics at each boundary', 'Объяснить процессы и признаки каждой границы')},
  {id:3,text:b('Describe Earth’s layers and their characteristics', 'Описать слои Земли и их характеристики')},
  {id:4,text:b('Explain earthquakes and distinguish focus from epicentre', 'Объяснить землетрясения и различить очаг и эпицентр')},
  {id:5,text:b('Compare composite shield fissure and caldera volcanoes', 'Сравнить стратовулканы, щитовые вулканы, трещинные извержения и кальдеры')},
  {id:6,text:b('Describe the structure of a volcano', 'Описать строение вулкана')},
  {id:7,text:b('Explain Chile and Nepal causes impacts and responses', 'Объяснить причины, последствия и меры реагирования в Чили и Непале')},
  {id:8,text:b('Explain Eyjafjallajökull causes impacts and responses', 'Объяснить причины, последствия и меры реагирования при извержении Эйяфьядлайёкюдля')},
  {id:9,text:b('Explain prediction protection and preparation', 'Объяснить прогнозирование, защиту и подготовку')},
  {id:10,text:b('Evaluate long-term building design management', 'Оценить долгосрочное управление строительством')},
];
const g = (en:string,ru:string,de:string,dr:string) => ({term:b(en,ru),definition:b(de,dr)});
export const glossary = [
  g('Crust','Земная кора','The outermost compositional layer; oceanic crust is generally thinner and denser than continental crust.','Внешний слой по составу; океаническая кора обычно тоньше и плотнее континентальной.'),
  g('Mantle','Мантия','The rocky layer below the crust, mostly solid but capable of very slow flow over geological time.','Каменный слой под корой, преимущественно твёрдый, но способный к очень медленному течению за геологическое время.'),
  g('Lithosphere','Литосфера','The rigid crust and uppermost mantle together, divided into tectonic plates.','Жёсткая кора вместе с самой верхней частью мантии, разделённая на плиты.'),
  g('Asthenosphere','Астеносфера','A weaker, deformable region of the upper mantle beneath the lithosphere.','Более слабая, деформируемая область верхней мантии под литосферой.'),
  g('Convection','Конвекция','Heat transfer through movement; mantle motion is extremely slow flow of mostly solid rock.','Перенос тепла движением вещества; движение мантии — крайне медленное течение преимущественно твёрдых пород.'),
  g('Slab pull','Тяга погружающейся плиты','A dense sinking slab pulls the rest of its plate toward a subduction zone.','Плотная погружающаяся часть тянет остальную плиту к зоне субдукции.'),
  g('Constructive or divergent','Конструктивная или дивергентная граница','Plates separate; rising material can melt as pressure falls and create new oceanic crust.','Плиты расходятся; поднимающееся вещество может плавиться при падении давления и создавать новую океаническую кору.'),
  g('Destructive subduction','Деструктивная граница субдукции','Plates converge and one slab descends beneath another.','Плиты сближаются, и одна погружается под другую.'),
  g('Collision','Коллизия','Continental convergence that shortens and thickens crust, creating large mountain belts.','Сближение континентов, которое укорачивает и утолщает кору, создавая крупные горные пояса.'),
  g('Conservative or transform','Консервативная или трансформная граница','Plates slide horizontally past each other; crust is not systematically created or destroyed there.','Плиты скользят горизонтально вдоль друг друга; кора здесь систематически не создаётся и не уничтожается.'),
  g('Subduction zone','Зона субдукции','The region in which a plate descends into the mantle beneath another plate.','Область, где одна плита погружается в мантию под другую.'),
  g('Fault','Разлом','A fracture or zone of fractures along which rock blocks move relative to one another.','Трещина или зона трещин, вдоль которой блоки пород перемещаются относительно друг друга.'),
  g('Elastic rebound','Упругая отдача','Strained rocks spring toward a less-deformed state when a locked fault suddenly slips.','Деформированные породы возвращаются к менее напряжённому состоянию при резком смещении сцепленного разлома.'),
  g('Focus or hypocentre','Очаг или гипоцентр','The point within Earth where an earthquake rupture begins.','Точка внутри Земли, в которой начинается разрыв при землетрясении.'),
  g('Epicentre','Эпицентр','The point on Earth’s surface directly above the focus.','Точка на поверхности Земли непосредственно над очагом.'),
  g('Magnitude','Магнитуда','A measure of earthquake size; moment magnitude Mw is used for the large events in these case studies.','Мера размера землетрясения; для крупных событий в этих кейсах используется моментная магнитуда Mw.'),
  g('Intensity','Интенсивность','The severity of shaking or its effects at a particular location; it varies across an earthquake’s affected area.','Сила сотрясения или его последствий в конкретном месте; различается по территории одного землетрясения.'),
  g('Aftershock','Афтершок','An earthquake in the affected region after a larger main shock, associated with readjustment of the fault system.','Землетрясение в затронутом районе после более сильного основного толчка, связанное с перестройкой напряжений.'),
  g('Tsunami','Цунами','A series of long waves produced by rapid displacement of a large volume of water.','Серия длинных волн, возникающая при быстром смещении большого объёма воды.'),
  g('Liquefaction','Разжижение грунта','Temporary loss of strength in susceptible saturated soils during shaking; it is not melting.','Временная потеря прочности восприимчивых водонасыщенных грунтов при толчках; это не плавление.'),
  g('Magma and lava','Магма и лава','Magma is molten or partly molten rock below ground; lava is magma erupted at the surface.','Магма — расплавленное или частично расплавленное вещество под землёй; лава — магма, вышедшая на поверхность.'),
  g('Viscosity','Вязкость','Resistance to flow; higher viscosity can hinder gas escape and favour explosive behaviour.','Сопротивление течению; высокая вязкость может затруднять выход газа и способствовать взрывному характеру извержения.'),
  g('Composite or stratovolcano','Стратовулкан','A volcanic cone built from successive lava and fragmental deposits, often with steep slopes.','Вулканический конус из последовательных лавовых и обломочных отложений, часто с крутыми склонами.'),
  g('Shield volcano','Щитовой вулкан','A broad, gently sloping volcano commonly built by relatively fluid basaltic lava.','Широкий пологий вулкан, обычно образованный относительно текучей базальтовой лавой.'),
  g('Fissure','Трещина','An elongated opening through which magma can erupt; it need not form a single cone.','Вытянутое отверстие, через которое может извергаться магма; один конус при этом не обязателен.'),
  g('Caldera','Кальдера','A large volcanic depression commonly formed by collapse after magma is withdrawn from a reservoir.','Крупная вулканическая впадина, обычно возникающая при обрушении после оттока магмы из резервуара.'),
  g('Vent and crater','Жерло и кратер','A vent is an outlet; a crater is a depression around an outlet. They are not interchangeable names.','Жерло — выходное отверстие, кратер — углубление вокруг выхода. Это не взаимозаменяемые названия.'),
  g('Dyke and sill','Дайка и силл','A dyke cuts across rock layers; a sill intrudes approximately parallel to them.','Дайка пересекает слои пород; силл внедряется примерно параллельно им.'),
  g('Pyroclastic flow','Пирокластический поток','A dangerous ground-hugging mixture of hot gas and volcanic particles moving downslope.','Опасная смесь горячего газа и вулканических частиц, движущаяся по поверхности вниз по склону.'),
  g('Lahar','Лахар','A flowing mixture of water and volcanic debris, often channelled along valleys.','Движущаяся смесь воды и вулканических обломков, часто текущая по долинам.'),
  g('Jökulhlaup','Йёкюльхлёйп','An outburst flood associated with glacial water, including meltwater released during some subglacial eruptions.','Прорывной ледниковый паводок, в том числе из талой воды при некоторых подледниковых извержениях.'),
  g('Primary and secondary effects','Первичные и вторичные последствия','Primary effects result directly from the event; secondary effects arise through triggered processes and disruption. State which event is your starting point.','Первичные последствия возникают непосредственно от события; вторичные — через запущенные им процессы и нарушения. Укажи, какое событие считаешь исходным.'),
  g('Hazard exposure and vulnerability','Опасность подверженность и уязвимость','The process, the people/assets in its path, and their susceptibility to harm respectively.','Соответственно: опасный процесс, люди и имущество в зоне его действия, их склонность понести ущерб.'),
  g('Resilience','Устойчивость сообщества','The ability to withstand, adapt to and recover from hazardous events while maintaining or restoring essential functions.','Способность выдерживать опасные события, адаптироваться и восстанавливаться, сохраняя или возвращая важные функции.'),
  g('Prediction protection preparation','Прогнозирование защита подготовка','Assess possible events; reduce exposure or vulnerability; organise the ability to act.','Оценивать возможные события; уменьшать подверженность или уязвимость; обеспечивать готовность действовать.'),
  g('Retrofit','Усиление существующего здания','Changes made to an existing structure to improve its performance during a hazard.','Изменения существующей конструкции для повышения её устойчивости к опасному воздействию.'),
  g('Ductility','Пластичность','Capacity to undergo substantial deformation without abrupt brittle failure.','Способность существенно деформироваться без внезапного хрупкого разрушения.'),
  g('Base isolation','Сейсмоизоляция','Engineered bearings that reduce the transfer of some ground motion into a structure.','Специальные опоры, уменьшающие передачу части колебаний грунта конструкции.'),
  g('Evaluate','Оценить','Weigh evidence, effectiveness and limitations, then reach a supported judgement.','Сопоставить данные, результативность и ограничения, затем сделать обоснованный вывод.'),
  g('Explain','Объяснить','Connect cause and consequence using a process; a list of facts alone is not an explanation.','Связать причину и следствие через механизм; одного перечня фактов недостаточно.'),
];

const source = (id:string,title:string,url:string,en:string,ru:string):Source => ({id,title,url,purpose:b(en,ru)});
export const sources:Source[] = [
  source('earth-usgs','USGS Inside the Earth','https://pubs.usgs.gov/gip/dynamic/inside.html','Earth layers and physical properties.','Слои Земли и физические свойства.'),
  source('plates-usgs','USGS Understanding plate motions','https://pubs.usgs.gov/gip/dynamic/understanding.html','Boundary types and global examples.','Границы плит и примеры.'),
  source('earthquakes-usgs','USGS The science of earthquakes','https://www.usgs.gov/programs/earthquake-hazards/science-earthquakes','Rupture, focus, epicentre and seismic waves.','Разрыв, очаг, эпицентр и сейсмические волны.'),
  source('volcanoes-usgs','USGS Principal types of volcanoes','https://pubs.usgs.gov/gip/volc/types.html','Volcanic forms and structures.','Формы и строение вулканов.'),
  source('bgs-volcanoes','BGS How volcanoes form','https://www.bgs.ac.uk/discovering-geology/earth-hazards/volcanoes/how-volcanoes-form/','Magma formation and tectonic settings.','Образование магмы и тектонические условия.'),
  source('magnitude-usgs','USGS Magnitude energy release and intensity','https://www.usgs.gov/programs/earthquake-hazards/earthquake-magnitude-energy-release-and-shaking-intensity','Distinguish event size from local shaking.','Различие размера события и местного сотрясения.'),
  source('glossary-usgs','USGS Volcano Hazards Program glossary','https://www.usgs.gov/glossary/volcano-hazards-program-glossary','Crater, caldera, magma and volcanic hazards.','Кратер, кальдера, магма и вулканические опасности.'),
  source('himalaya-usgs','USGS Seismicity of the Himalaya','https://www.usgs.gov/publications/seismicity-earth-1900-2010-himalaya-and-vicinity','Continental convergence and underthrusting.','Континентальное сближение и поддвиг.'),
  source('magma-usgs','USGS Magma supply storage and transport','https://www.usgs.gov/publications/magma-supply-storage-and-transport-shield-stage-hawaiian-volcanoes','Connected storage regions and magma transport.','Связанные области накопления и перенос магмы.'),
  source('subduction-usgs','USGS This Dynamic Planet','https://pubs.usgs.gov/imap/2800/TDPback-screen.pdf','Plate processes and water-assisted melting.','Процессы плит и плавление при участии воды.'),
  source('risk-undrr','UNDRR Disaster risk','https://www.undrr.org/terminology/disaster-risk','Hazard, exposure, vulnerability and capacity.','Опасность, подверженность, уязвимость и возможности.'),
  source('prediction-usgs','USGS Can you predict earthquakes','https://www.usgs.gov/faqs/can-you-predict-earthquakes','Limits of exact prediction.','Пределы точного предсказания.'),
  source('warning-usgs','USGS Comparison of earthquake and volcano early warning','https://pubs.usgs.gov/publication/fs20233033/full','Detection after rupture versus forecasting volcanic unrest.','Обнаружение после разрыва и прогнозирование вулканической активности.'),
  source('monitoring-usgs','USGS Monitoring data and eruption forecasts','https://www.usgs.gov/programs/VHP/vhp-uses-monitoring-data-and-volcanic-history-forecast-eruptions','Seismicity, deformation, gases and uncertainty.','Сейсмичность, деформация, газы и неопределённость.'),
  source('tsunami-noaa','NOAA Before a tsunami','https://www.weather.gov/safety/tsunami-before','Natural warnings and evacuation preparation.','Естественные предупреждения и подготовка к эвакуации.'),
  source('fema-design','FEMA Earthquake Resistant Design Concepts','https://www.fema.gov/sites/default/files/2020-07/fema_earthquake-resistant-design-concepts_p-749.pdf','Structural principles, ductility and protective systems.','Принципы конструкций, пластичность и защитные системы.'),
  source('fema-homes','FEMA Homebuilders Guide P232','https://www.fema.gov/sites/default/files/documents/fema_p-232_september2024.pdf','Connections, load paths and retrofit.','Соединения, передача нагрузок и усиление.'),
  source('ground-usgs','USGS Effects of earthquakes','https://www.usgs.gov/programs/earthquake-hazards/what-are-effects-earthquakes','Ground failure, liquefaction and site effects.','Нарушения грунта, разжижение и условия площадки.'),
  source('school-unesco','UNESCO Education and school safety','https://www.unesco.org/en/disaster-risk-reduction/school-safety','Safe facilities and preparedness in education.','Безопасные здания и подготовка в образовании.'),
  source('recovery-nist','NIST Functional recovery of buildings and lifelines','https://www.nist.gov/programs-projects/functional-recovery-buildings-and-lifelines','Life safety, nonstructural damage and restoring services.','Сохранение жизни, повреждение систем и восстановление услуг.'),
  source('ash-usgs','USGS Volcanic ash roof loading','https://volcanoes.usgs.gov/volcanic_ash/roof_loading.html','Ash weight and roof vulnerability.','Вес пепла и уязвимость крыш.'),
  ...caseSources,
];
